CREATE TABLE SERIES
(
    ID_SERIES INT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(200)
);

INSERT INTO SERIES (ID_SERIES, TITLE)
VALUES (1, 'ONE PIECE');

CREATE TABLE CHAPTERS
(
    CHAPTER_NO INT PRIMARY KEY NOT NULL,
    TITLE    VARCHAR(200) NOT NULL,
    STATUS    VARCHAR(100) NOT NULL,
    ID_SERIES INT NOT NULL,
    FOREIGN KEY (ID_SERIES) REFERENCES SERIES (ID_SERIES)
);

INSERT INTO CHAPTERS (CHAPTER_NO, TITLE, STATUS, ID_SERIES)
VALUES (1, '¡Yo soy Luffy! ¡El próximo rey de los piratas!', 'CANON', 1),
       (2, '¡Aparece el gran espadachín! El cazador de piratas Roronoa Zoro', 'CANON', 1),
       (3, '¡Morgan contra Luffy! ¿Quién es esta hermosa joven?', 'CANON', 1),
       (4, '¡El pasado de Luffy! ¡Aparece el pelirrojo Shanks!', 'CANON', 1),
       (5, '¡Teme el misterioso poder! ¡El capitán payaso Buggy!', 'CANON', 1),
       (6, '¡Situación desesperada! ¡El domador de bestias Mohji contra Luffy!', 'CANON', 1),
       (7, '¡Gran duelo! ¡Zoro el espadachín contra Cabaji el acróbata!', 'CANON', 1),
       (8, '¿Quién ganará? ¡Enfrentamiento decisivo entre los verdaderos poderes del diablo!', 'CANON', 1),
       (9, '¿Mentiroso honorable? El capitán Usopp', 'CANON', 1),
       (10, '¡El tío más raro del mundo! Jango, el hipnotizador', 'CANON', 1),
       (11, '¡Destapando la conspiración! El mayordomo es el capitán Kuro', 'CANON', 1),
       (12, '¡Batalla! La banda pirata de Kuroneko ¡Enfrentamiento en la cuesta!', 'CANON', 1),
       (13, 'La pareja asesina. Los hermanos Nyaban contra Zorro', 'CANON', 1),
       (14, 'Luffy despierta. La impotencia de la señorita Kaya', 'CANON', 1),
       (15, '¡Derrotar a Kuro! ¡La determinación llena de lágrimas de Usopp!', 'CANON', 1),
       (16, '¡Proteged a Kaya! ¡La banda pirata de Usopp entra en acción!', 'CANON', 1),
       (17, 'El enfrentamiento entre Kuro y Luffy', 'CANON', 1),
       (18, 'Gaimon el raro y sus extraños amigos', 'CANON', 1),
       (19, '¡La historia de las tres espadas! ¡La promesa entre Zoro y Kuina!', 'CANON', 1),
       (20, 'El famoso cocinero del restaurante maritimo Sanji', 'CANON', 1),
       (21, 'El invitado especial. Gin agradece la bondad de Sanji', 'CANON', 1),
       (22, 'La flota pirata del terrible capitan Krieg', 'CANON', 1),
       (23, '¡Proteged el Baratie! El gran pirata, Pierna Roja Zeff', 'CANON', 1),
       (24, '¡Zoro el espadachín cae al mar! ¡Mihawk Ojos de Halcón!', 'CANON', 1),
       (25, '¡Impresionantes habilidades con las piernas! Sanji contra Pearl Muro de Hierro', 'CANON', 1),
       (26, 'El sueño de Zeff y Sanji: El mar de ensueño, All Blue', 'CANON', 1),
       (27, 'El hombre de gélido corazón. Gin, el comandante del escuadrón de asalto', 'CANON', 1),
       (28, 'Un duelo a muerte. El enfrentamiento', 'CANON', 1),
       (29, 'El final de la batalla. La fuerza de un simple puñetazo', 'CANON', 1),
       (30, 'La despedida de Sanji', 'CANON', 1),
       (31, '¡El mayor criminal del East Blue! ¡Arlong de los piratas Gyojin!', 'CANON', 1),
       (32, '¡La bruja de Kokoyashi! La oficial de Arlong', 'CANON', 1),
       (33, '¿¡La muerte de Usopp!? Luffy, ¿Aún no has llegado?', 'CANON', 1),
       (34, '¡Reunidos! Usopp cuenta la auténtica historia de Nami', 'CANON', 1),
       (35, 'El pasado oculto. La historia de Bellemere', 'CANON', 1),
       (36, 'El lazo de sangre entre Nami y Bellemere', 'CANON', 1),
       (37, 'La promesa incumplida. La respuesta de Luffy', 'CANON', 1),
       (38, '¡Luffy en problemas! Gyojin contra los piratas de Luffy', 'CANON', 1),
       (39, '¡Luffy se ahoga! Zoro contra el pulpo Hatchan', 'CANON', 1),
       (40, '¡El orgullo de grandes guerreros! La dramática batalla de Sanji y Usopp', 'CANON', 1),
       (41, '¡Lo mejor de Luffy! ¡El valor de Nami y Sombrero de Paja!', 'CANON', 1),
       (42, '¡Disparando! ¡El temible ataque desde el mar del Gyojin Arlong!', 'CANON', 1),
       (43, '¡El final del imperio Gyojin! ¡Nami es mi amiga!', 'CANON', 1),
       (44, '¡Adiós con una sonrisa! Hasta siempre, pueblo de Kokoyashi, mi hogar', 'CANON', 1),
       (45, '¡Recompensa! Monkey D. Luffy es conocido en todo el mundo', 'MIXTO', 1),
       (46, '¡Encontrar a Sombrero de Paja! La gran aventura del pequeño Buggy', 'MIXTO', 1),
       (47, 'El regreso del capitan Buggy', 'MIXTO', 1),
       (48, 'Loguetown, la ciudad del principio y el final', 'MIXTO', 1),
       (49, 'Las espadas nuevas de Zoro y la sargento mayor Tashigi', 'MIXTO', 1),
       (50, 'Usopp contra Daddy el padre ¡Ajuste de cuentas al medio día!', 'RELLENO', 1),
       (51, '¿Un duelo culinario? Sanji contra la guapísima cocinera', 'RELLENO', 1),
       (52, '¡La venganza de Buggy! El hombre que sonrió en la plataforma de ejecución', 'CANON', 1),
       (53, '¡Comienza la leyenda! Directos a la Grand Line', 'CANON', 1),
       (54, '¡El presagio de una nueva aventura! La chica misteriosa Apis', 'RELLENO', 1),
       (55, '¡El bestia sagrada! El secreto de Apis y la isla legendaria.', 'MIXTO', 1),
       (56, '¡El asalto de Erik! La gran huída de la Isla Gunkan', 'RELLENO', 1),
       (57, '¡Una isla solitaria en un lejano mar! La legendaria Lost Island', 'RELLENO', 1),
       (58, '¡Duelo en las ruinas! Zoro contra Erik', 'RELLENO', 1),
       (59, '¡Luffy completamente rodeado! El plan secreto del almirante Nelson', 'RELLENO', 1),
       (60, '¡Aquellos que planean sobre el cielo abierto! Resurgir tras mil años', 'RELLENO', 1),
       (61, 'Final angustioso. ¡Crucemos la Red Line!', 'MIXTO', 1),
       (62, '¿El primer obstáculo? Aparece Laboon, la ballena gigante', 'CANON', 1),
       (63, '¡La promesa de un hombre! Luffy y la promesa de la ballena de volverse a encontrar', 'CANON', 1),
       (64, '¿Una ciudad que ama a los piratas? Llegada a Whiskey Peak', 'CANON', 1),
       (65, '¡Santoryuu explosivo! Zoro contra Baroque Works', 'CANON', 1),
       (66, '¡Un combate en serio! ¡Luffy contra Zoro: el duelo inesperado!', 'CANON', 1),
       (67, '¡Entregar a la princesa Vivi! La partida de los piratas de Luffy', 'CANON', 1),
       (68, '¡Da todo lo que tienes, Coby! El diario de entrenamiento como Marines de Coby y Helmeppo', 'MIXTO', 1),
       (69, '¡La determinación de Coby y Helmeppo! El orgullo paternal del vicealmirante Garp', 'MIXTO', 1),
       (70, '¡La isla prehistórica! La sombra que se cierne sobre Little Garden', 'CANON', 1),
       (71, '¡La gran batalla! Los gigantes Dorry y Brogy!', 'CANON', 1),
       (72, '¡La furia de Luffy! Una sucia artimaña en una batalla sagrada', 'CANON', 1),
       (73, '¡Los llantos de Brogy por la victoria! El Juicio de Elbaf', 'CANON', 1),
       (74, '¡La Vela del Diablo! Lágrimas de pesar y lágrimas de cólera', 'CANON', 1),
       (75, '¡Luffy es atacado con magia! La trampa de los colores', 'CANON', 1),
       (76, '¡Contraataque crítico! ¡El ingenio de Usopp y sus Kaenboshi!', 'CANON', 1),
       (77, '¡Hasta siempre, isla de los gigantes! Directos a Arabasta', 'CANON', 1),
       (78, '¿Nami cae enferma? Más allá de la nieve que cae en el mar', 'CANON', 1),
       (79, '¡Emboscada! El Bliking y Wapol el Blik', 'CANON', 1),
       (80, '¿Una isla sin médicos? ¡Aventura en el país sin nombre!', 'CANON', 1),
       (81, '¿Eres feliz? ¡La doctora a la que llaman bruja!', 'CANON', 1),
       (82, '¡La determinación de Dalton! Las fuerzas de Wapol toman tierra', 'CANON', 1),
       (83, '¡Los que viven en la isla de nieve! Escalando las Rocosas de Drum', 'CANON', 1),
       (84, '¡El reno de la nariz azul! El secreto de Chopper', 'CANON', 1),
       (85, '¡El sueño de un paria! El curandero Hiruluk', 'CANON', 1),
       (86, 'Las flores de cerezo de Hiruluk y la voluntad heredada', 'CANON', 1),
       (87, '¡Contra las fuerzas armadas de Wapol! Las habilidades de la fruta Baku Baku', 'CANON', 1),
       (88, '¡Fruta del demonio de la familia Zoan! Las siete transformaciones de Chopper', 'CANON', 1),
       (89, '¡Cuando la dictadura de un reino acaba! La bandera de la convicción perdura por siempre', 'CANON', 1),
       (90, '¡Las flores de cerezo de Hiruluk! Milagro en las Rocosas de Drum', 'CANON', 1),
       (91, '¡Adiós, isla de Drum! ¡Me voy al mar!', 'CANON', 1),
       (92, 'El héroe de Arabasta y la bailarina en la cubierta', 'CANON', 1),
       (93, '¡Llegando al reino del desierto! El polvo que llama a la lluvia y el ejército rebelde', 'MIXTO', 1),
       (94, '¡Reunión de los más poderosos! Su nombre es Ace Puño de Fuego', 'MIXTO', 1),
       (95, '¡Ace y Luffy! Cálidos recuerdos y vínculos fraternales', 'MIXTO', 1),
       (96, 'La ciudad verde, Erumalu y los Kung Fu Dugongs', 'CANON', 1),
       (97, '¡Aventura en al país de la arena! Los monstruos que viven en la tierra abrasadora', 'MIXTO', 1),
       (98, '¡Aparecen los piratas de las arenas! Los hombres que viven en libertad', 'MIXTO', 1),
       (99, '¡El espíritu de un impostor! Kamyu, el corazón del ejército rebelde', 'RELLENO', 1),
       (100, '¡El guerrero rebelde, Kohza! ¡El sueño jurado a Vivi!', 'CANON', 1),
       (101, '¡Duelo de ondas de calor! Ace contra Scorpion', 'MIXTO', 1),
       (102, '¡Ruinas y perdidos! Vivi, la verdadera amistad y la forma de un país', 'RELLENO', 1),
       (103, 'Los cabecillas del enemigo se encuentran en el Spider Cafe a las ocho en punto', 'CANON', 1),
       (104, '¡Luffy contra Vivi! Un voto con lágrimas por una amiga', 'CANON', 1),
       (105, '¡El frente de guerra de Arabasta! La ciudad de los sueños, Rainbase', 'CANON', 1),
       (106, '¡Trampa de final absoluto! Irrumpiendo en Rain Dinners', 'CANON', 1),
       (107, '¡Comienza la Operación Utopía! La ola de rebelión empieza a moverse', 'CANON', 1),
       (108, 'El feroz Bananawani y Mr. Prince', 'CANON', 1),
       (109, '¡La llave para volver y la gran huida! ¡Doru Doru Ball!', 'CANON', 1),
       (110, '¡Combate a muerte sin piedad! Luffy contra Crocodile', 'CANON', 1),
       (111, '¡El sprint milagroso! Arabasta, el país animal', 'CANON', 1),
       (112, '¡Ejército rebelde contra ejército Real! ¡La batalla será en Alubarna!', 'CANON', 1),
       (113, '¡Alubarna llora! ¡La feroz batalla del capitán Carue!', 'CANON', 1),
       (114, '¡Fe en el sueño de tu amigo! Batalla en la cuarta base de la topera', 'CANON', 1),
       (115, '¡La gran función de hoy! Mane Mane Montage', 'CANON', 1),
       (116, '¡Transformándose en Nami! El devastador Ballet Kenpo de Bon Kure', 'CANON', 1),
       (117, '¡El barómetro de presiones de Nami! El Clima Tact explota', 'CANON', 1),
       (118, '¡El secreto de la Familia Real! El arma ancestral, Plutón', 'CANON', 1),
       (119, '¡La esencia de una espada poderosa! El poder de cortar el acero y el aliento de todas las cosas', 'CANON',
        1),
       (120, '¡La batalla ha terminado! Kohza ondea la bandera blanca', 'CANON', 1),
       (121, '¡La voz de Vivi no se oye! ¡Llega un héroe!', 'CANON', 1),
       (122, '¡Cocodrilo de arena y Luffy de agua! Segunda ronda del combate a muerte', 'CANON', 1),
       (123, '¡Huele a cocodrilo! ¡Corre hasta la tumba de la Familia Real, Luffy!', 'CANON', 1),
       (124, '¡La pesadilla de acerca! La base secreta del clan Suna Suna', 'CANON', 1),
       (125, '¡Magníficas alas! Mi nombre es Pell, espíritu guardián de Arabasta', 'CANON', 1),
       (126, '¡Te superaré! ¡La lluvia cae sobre Arabasta!', 'CANON', 1),
       (127, '¡Adiós a la armas! Piratas y un poco de justicia', 'CANON', 1),
       (128, 'El banquete de los piratas y la operación huida de Arabasta', 'CANON', 1),
       (129, '¡Todo comenzó ese día! Vivi cuenta sus aventuras', 'CANON', 1),
       (130, '¡Cuidado con su fragancia! El séptimo de a bordo es Nico Robin', 'CANON', 1),
       (131, '¡El primer paciente! La anécdota de la Rumble Ball', 'RELLENO', 1),
       (132, '¡El motín de la navegante! ¡Por un sueño firme!', 'RELLENO', 1),
       (133, '¡La receta heredada! Sanji, el experto en curry', 'RELLENO', 1),
       (134, '¡La haré florecer! La bola 8-Shaku del varonil Usopp', 'RELLENO', 1),
       (135, '¡El infame cazador de piratas! El espadachín errante, Zoro', 'RELLENO', 1),
       (136, '¡Zenny de la Isla de las Cabras y el barco pirata en las montañas!', 'RELLENO', 1),
       (137, '¿Trato hecho? ¡La ambición de Zenny el prestamista!', 'RELLENO', 1),
       (138, '¡El escondite del tesoro! ¡Piratas de Zenny, a la carga!', 'RELLENO', 1),
       (139, '¡La leyenda de la Niebla Arcoíris! El viejo Henzo y la Isla Ruruka', 'RELLENO', 1),
       (140, '¡Los habitantes de Nunca Jamás! ¡Los piratas de la Calabaza!', 'RELLENO', 1),
       (141, '¡Añoranza del hogar! ¡El ineludible cementerio de piratas!', 'RELLENO', 1),
       (142, '¡Confusión y lucha inevitable! La ambición de Whetton y la torre Arcoíris', 'RELLENO', 1),
       (143, '¡Comienza la leyenda! Más allá de la niebla', 'MIXTO', 1),
       (144, '¡Dirección imposible! Masira, el rey del reflotamiento', 'CANON', 1),
       (145, '¡Aparece un monstruo! No os acerquéis a los piratas de Shirohige', 'CANON', 1),
       (146, 'Mock Town, la ciudad donde los sueños no existen', 'CANON', 1),
       (147, '¡Los mejores piratas! El hombre que hablaba de sueños y el rey de la exploración submarina', 'CANON', 1),
       (148, '¡La familia legendaria! Norland el mentiroso', 'CANON', 1),
       (149, '¡Rumbo al cielo! A cazar el Pájaro del Sur', 'CANON', 1),
       (150, '¡¿Los sueños no se hacen realidad?! Bellamy contra la alianza Saruyama', 'CANON', 1),
       (151, '¡El hombre de los 100 millones de Berries! La mayor autoridad del mundo y el pirata Kurohige', 'CANON',
        1),
       (152, '¡A toda vela hacia el cielo! Sobre la corriente del Knock-Up', 'CANON', 1),
       (153, '¡Estamos en el mar de las nubes! El caballero del cielo y la puerta celestial', 'CANON', 1),
       (154, '¡Skypiea, la tierra de Dios! Ángeles en la playa de las nubes', 'CANON', 1),
       (155, '¡La santuario prohibido! La tierra donde vive Dios y el Juicio Divino', 'CANON', 1),
       (156, '¡¿Ya somos criminales?! Los defensores de la ley en Skypiea', 'CANON', 1),
       (157, '¡¿Podremos escapar?! ¡El Juicio de Dios ha comenzado!', 'CANON', 1),
       (158, '¡Trampa en Lovely Street! El todopoderoso dios Enel', 'CANON', 1),
       (159, '¡Adelante Pequeño Cuervo! Hacia el altar de los sacrificios', 'CANON', 1),
       (160, '¡Probabilidad de sobrevivir: 10%! El sacerdote Satori, el maestro del Mantra', 'CANON', 1),
       (161, '¡El Juicio de la Bola! Lucha a muerte en el bosque perdido', 'CANON', 1),
       (162, '¡Chopper en peligro! El antiguo dios contra el sacerdote Shura', 'CANON', 1),
       (163, '¡Que misterio! ¡¿El Juicio de la Cuerda y del Amor?!', 'CANON', 1),
       (164, '¡Proteged nuestra tierra! El Guerrero Wiper', 'CANON', 1),
       (165, '¡Jaya y la isla de oro están en el cielo! ¡Todos hacia el santuario sagrado!', 'CANON', 1),
       (166, '¡El festival del oro y origen del Vearth', 'CANON', 1),
       (167, '¡Aparece el Dios Enel! Amanece para los supervivientes', 'CANON', 1),
       (168, '¡La serpiente gigante! ¡Empieza el juego de supervivencia!', 'CANON', 1),
       (169, '¡El peligroso dial de rechazo! La determinación del guerrero Wiper', 'CANON', 1),
       (170, '¡Batalla feroz en el cielo! El pirata Zoro contra el guerrero Braham', 'CANON', 1),
       (171, '¡El destructor bazooka de llamas! Luffy contra el diablo luchador Wiper', 'CANON', 1),
       (172, '¡El Juicio del Pantano! Chopper contra el sacerdote Gedatsu', 'CANON', 1),
       (173, '¡La habilidad invencible! Se revela la auténtica naturaleza de Enel', 'CANON', 1),
       (174, '¡La ciudad desaparecida! Las ruinas de la gran Shandora', 'CANON', 1),
       (175, '¡Probabilidad de supervivencia: 0%! Chopper contra el sacerdote Ohm', 'CANON', 1),
       (176, '¡Ascensión a la enredadera gigante! Confrontación en las ruinas de Shandora', 'CANON', 1),
       (177, '¡El Juicio del Hierro! Combate a muerte en la jaula de alambre espinado', 'CANON', 1),
       (178, '¡El ataque mortífero! Zoro contra el sacerdote Ohm', 'CANON', 1),
       (179, '¡Las antiguas ruinas se derrumban! El quinteto finalista', 'CANON', 1),
       (180, '¡Gran demostración en las ruinas de Shandora! ¡El objetivo del dios Enel!', 'CANON', 1),
       (181, 'Viaje al Vearth Eterno ¡El arca Maxim!', 'CANON', 1),
       (182, '¡Al fin se enfrentan! ¡El pirata Luffy contra el dios Enel!', 'CANON', 1),
       (183, '¡El arca Maxim despega! Comienza la Operación Deathpiea', 'CANON', 1),
       (184, '¡Luffy cae! El Juicio de Dios y el deseo de Nami', 'CANON', 1),
       (185, '¡Dos que despiertan! Operación de rescate ardiente en nombre del amor', 'CANON', 1),
       (186, '¡Situación desesperada! La inminente desaparición de Skypiea', 'CANON', 1),
       (187, '¡Guiados por el repicar de la campana! Cuento sobre el gran guerrero y el explorador', 'CANON', 1),
       (188, '¡Liberados de la desgracia! Las lágrimas de un gran guerrero', 'CANON', 1),
       (189, '¡Amistad eterna! La campana del juramento que resuena a lo largo del mar', 'CANON', 1),
       (190, '¡La Isla de los Ángeles destruida! El horrible advenimiento de Raigoh', 'CANON', 1),
       (191, '¡Derribando la enredadera gigante! La última esperanza de escapar', 'CANON', 1),
       (192, '¡Milagro en Skypiea! ¡La canción de amor que oyeron los ángeles!', 'CANON', 1),
       (193, '¡El final de la batalla! El orgullo de Shandora resuena en la lejanía', 'CANON', 1),
       (194, '¡Hasta aquí he llegado! El hilo que teje el Poneglyph', 'CANON', 1),
       (195, '¡Hacia el mar azul! Un sincero final triunfal', 'CANON', 1),
       (196, '¡Se declara el estado de emergencia! ¡La notoria infiltración del infame barco pirata!', 'RELLENO', 1),
       (197, '¡El cocinero Sanji! Demostrando su orgullo en el comedor de La Marina', 'RELLENO', 1),
       (198, '¡El encarcelamiento de Zoro y la operación de emergencia de Chopper!', 'RELLENO', 1),
       (199, '¡Se estrecha el cerco de los marines! ¡La segunda persona capturada!', 'RELLENO', 1),
       (200, '¡La crucial decisión de Luffy y Sanji! ¡Una gran maniobra de rescate!', 'RELLENO', 1),
       (201, '¡La participación de la unidad especial de sangre caliente! ¡Batalla en el puente!', 'RELLENO', 1),
       (202, '¡Destrozar la barricada y recuperar el Going Merry!', 'RELLENO', 1),
       (203, '¡La desaparición del barco pirata! Segundo round del asalto en la fortaleza', 'MIXTO', 1),
       (204, '¡Los planes para recuperar el oro y el waver!', 'RELLENO', 1),
       (205, '¡Atrapadlos a todos en la red! El astuto plan de Jonathan', 'RELLENO', 1),
       (206, '¡Adiós, cuartel de La Marina! La batalla final por la libertad', 'RELLENO', 1),
       (207, '¡Gran aventura en Long Ring Long Land!', 'CANON', 1),
       (208, '¡Los piratas de Foxy y el Davy Back Fight!', 'CANON', 1),
       (209, '¡La primera prueba! Una vuelta al Donut Race', 'CANON', 1),
       (210, '¡Foxy el Zorro Plateado! Un feroz ataque de obstrucción', 'CANON', 1),
       (211, '¡Segunda ronda! ¡Lanzamiento en el Groggy Ring!', 'CANON', 1),
       (212, '¡Rápida sucesión de Red Cards en el Groggy Ring!', 'CANON', 1),
       (213, '¡La tercera ronda! Rodando en la carrera de patines', 'RELLENO', 1),
       (214, '¡El punto álgido de la veloz carrera! Metiéndose en la última ronda', 'RELLENO', 1),
       (215, '¡Gritando al servicio veloz! ¡Dodgeball pirata!', 'MIXTO', 1),
       (216, '¡Lucha final en el acantilado! ¡Dharma-san ha caído!', 'RELLENO', 1),
       (217, '¡Capitán contra capitán! ¡El último combate!', 'CANON', 1),
       (218, 'Noro-Noro al máximo poder contra el inmortal Luffy', 'CANON', 1),
       (219, '¡Feroz y heróica lucha en el combate! El final queda decidido', 'CANON', 1),
       (220, '¿Perdida? ¿Robada? ¿Tú quién eres?', 'RELLENO', 1),
       (221, 'El misterioso chico de la flauta y el descubrimiento de Robin', 'RELLENO', 1),
       (222, '¡Recuperemos nuestra memoria! Desembarco en la isla de los piratas', 'RELLENO', 1),
       (223, '¡Zoro afila sus colmillos! ¡Combate contra un animal salvaje!', 'RELLENO', 1),
       (224, '¡El ataque final del ladrón de memorias!', 'RELLENO', 1),
       (225, '¡El hombre de gran orgullo! El Zorro Plateado, Foxy', 'MIXTO', 1),
       (226, '¿Un poder invencible descansa cerca? ¡El hombre más peligroso!', 'MIXTO', 1),
       (227, '¡Almirante del Cuartel General de La Marina, Aokiji! ¡La amenaza del mayor poder militar!', 'CANON', 1),
       (228, '¡Goma contra hielo! Combate uno contra uno, Luffy vs Aokiji', 'CANON', 1),
       (229, 'El veloz Umi Ressha y la Capital del Agua, Water 7', 'CANON', 1),
       (230, '¡Aventura en la Capital del Agua! En busca del gran astillero', 'CANON', 1),
       (231, 'La familia Franky e Iceburg-san', 'CANON', 1),
       (232, '¡Galley-La Company! El gran muelle 1', 'CANON', 1),
       (233, 'El secuestro del pirata y el barco que espera su muerte', 'CANON', 1),
       (234, '¡Rescate de un compañero! Incursión en la Franky House', 'CANON', 1),
       (235, '¡Gran combate a la luz de la Luna! El barco pirata que tiembla de tristeza', 'CANON', 1),
       (236, '¡Luffy contra Usopp! El carácter enfrentado de dos hombres', 'CANON', 1),
       (237, '¡La ciudad de agua tiembla! ¡Iceburg es el objetivo!', 'CANON', 1),
       (238, 'Hombre gomu gomu contra cyborg escupe fuego', 'CANON', 1),
       (239, '¿Los criminales son la banda de Sombrero de Paja? Los guardianes de Water 7', 'CANON', 1),
       (240, '¿Despedida final? Nico Robin, la mujer que lleva consigo la oscuridad', 'CANON', 1),
       (241, '¡Atrapad a Robin! La decisión de la banda de Sombrero de Paja', 'CANON', 1),
       (242, '¡La explosión es la señal! El CP9 empieza a moverse', 'CANON', 1),
       (243, '¡CP9 desenmascarado! Los auténticos rostros al descubierto', 'CANON', 1),
       (244, '¡El vínculo oculto! Iceburg y Franky', 'CANON', 1),
       (245, '¡Vuelve con nosotros, Robin! ¡Confrontación con el CP9!', 'CANON', 1),
       (246, '¿La aniquilación de los piratas de Sombero de Paja? ¡El terror del modelo leopardo!', 'CANON', 1),
       (247, '¡El amor de un hombre por su barco! ¡Las lágrimas de Usopp!', 'CANON', 1),
       (248, '¡El pasado de Franky! El día en que el Umi Ressha partió', 'CANON', 1),
       (249, '¡La conspiración de Spandam! El día en que el Umi Ressha tembló', 'CANON', 1),
       (250, '¡El final de un hombre legendario! El día en que el Umi Ressha lloró', 'CANON', 1),
       (251, '¡La verdad tras la traición! ¡La dolorosa decisión de Robin!', 'CANON', 1),
       (252, '¡El silbido separa a los amigos! El Umi Ressha se pone en marcha', 'CANON', 1),
       (253, '¡Sanji a la carga! ¡Batalla en el Umi Ressha bajo la tormenta!', 'CANON', 1),
       (254, '¡La protesta de Nami desde su corazón! ¡El regreso de Sombrero de Paja Luffy!', 'CANON', 1),
       (255, '¿¡Otro Umi Ressha!? ¡La salida del Rocket Man!', 'CANON', 1),
       (256, '¡Rescatemos a nuestros amigos! ¡Rivales unidos con sus puños!', 'CANON', 1),
       (257, '¡Rompamos la ola! ¡El combo definitivo de Luffy y Zoro!', 'CANON', 1),
       (258, '¿¡Aparece un hombre misterioso!? ¡Su nombre es Sogeking!', 'CANON', 1),
       (259, '¡Confrontación entre cocineros! Sanji contra Ramen Kenpo', 'CANON', 1),
       (260, '¡Duelo en el techo! Franky contra Nero', 'CANON', 1),
       (261, '¡Choque! Zoro el cortademonios contra T-Bone el cortabarcos', 'CANON', 1),
       (262, '¡La lucha de Robin! ¡El astuto plan de Sogeking!', 'CANON', 1),
       (263, '¡La isla judicial! ¡El paisaje triunfal de Enies Lobby!', 'CANON', 1),
       (264, '¡Comienza la operación de desembarco! ¡Acometida de la banda de Sombrero de Paja!', 'CANON', 1),
       (265, '¡Luffy a la carga! ¡La gran batalla decisiva en la isla judicial!', 'CANON', 1),
       (266, '¡Batalla contra los gigantes! ¡Abramos la segunda puerta!', 'CANON', 1),
       (267, '¡La vía de escape se abre! ¡Vuela por el cielo, Rocket Man!', 'CANON', 1),
       (268, '¡Reunámonos con Luffy! ¡La guerra total de los piratas de Sombrero de Paja!', 'CANON', 1),
       (269, '¡Robin ha sido traicionada! ¡Las expectativas del Gobierno Mundial!', 'CANON', 1),
       (270, '¡Devolvednos a Robin! ¡Luffy contra Blueno!', 'CANON', 1),
       (271, '¡No os detengáis! ¡Dad la señal del contraataque!', 'CANON', 1),
       (272, '¡Luffy a la vista! ¡Reunión en la plaza del Palacio Judicial!', 'CANON', 1),
       (273, '¡Todo para poder proteger a mis amigos! ¡Gia Sekando en movimiento!', 'CANON', 1),
       (274, '¡Respóndenos, Robin! ¡La protesta de la banda de Sombrero de Paja!', 'CANON', 1),
       (275, '¡El pasado de Robin! ¡La niña que fue llamada demonio!', 'CANON', 1),
       (276, '¡Madre e hija predestinadas! ¡El nombre de la madre es Olvia!', 'CANON', 1),
       (277, '¡Tragedia en Ohara! ¡Terror por la Buster Call!', 'CANON', 1),
       (278, '¡Dime que quieres vivir! ¡Somos tus amigos!', 'CANON', 1),
       (279, '¡Lanzarse por el precipicio! ¡Los sentimientos de Luffy!', 'RELLENO', 1),
       (280, '¡El modo de vivir de un hombre! Las técnicas de Zoro y el sueño de Usopp', 'RELLENO', 1),
       (281, '¡Las lágrimas que tejieron los lazos entre amigos! El mapa del mundo de Nami', 'RELLENO', 1),
       (282, '¡La despedida mejora a un hombre! Sanji y Chopper', 'RELLENO', 1),
       (283, '¡Todo por un amigo! La oscuridad de Robin', 'RELLENO', 1),
       (284, '¡No voy a entregarte los planos! La decisión de Franky', 'CANON', 1),
       (285, '¡Hagámonos con las cinco llaves! Los Sombrero de Paja contra el CP9', 'CANON', 1),
       (286, '¡El poder de las Frutas del Demonio! ¡La transformación de Kaku y Jabura!', 'CANON', 1),
       (287, '¡Aunque me cueste la vida no te golpearé! El camino de la caballerosidad de Sanji', 'CANON', 1),
       (288, '¡El error de cálculo de Fukurou! La cola es mi agua de vida', 'CANON', 1),
       (289, '¡Zoro estalla con una nueva técnica! ¿La nueva espada de Zoro es Sogeking?', 'CANON', 1),
       (290, '¡Incontrolable! ¡La Rumble Ball prohibida de Chopper!', 'CANON', 1),
       (291, '¡El regreso de Luffy Oyabun! Sueño o realidad, problemas con la lotería', 'RELLENO', 1),
       (292, '¡La gran carrera Mochi Maki hacia el castillo! La conspiración de la Nariz Roja', 'RELLENO', 1),
       (293, '¡Califa usa burbujas! Nami se acerca a la trampa del jabón', 'CANON', 1),
       (294, '¡Los ecos de una terrible noticia! ¡La Buster Call invocada!', 'CANON', 1),
       (295, '¿Cinco Namis? Contraataque con espejismos', 'CANON', 1),
       (296, '¡La determinación de Nami! ¡Disparad al enloquecido Chopper!', 'CANON', 1),
       (297, '¿Aparece Sanji el cazador? Una elegía para el lobo mentiroso', 'CANON', 1),
       (298, '¡La patada ardiente! El juego de pies Full-Course de Sanji', 'CANON', 1),
       (299, '¡Un ataque furioso de espadas desenvainadas! Zoro contra Kaku: Un poderoso duelo de cortes', 'CANON', 1),
       (300, '¡Kishin Zoro! La encarnación de Ashura mostrada por su espíritu', 'CANON', 1),
       (301, '¡Spandam se sorprende! El héroe que permanece de pie en la Torre de la Justicia', 'CANON', 1),
       (302, '¡Robin liberada! Luffy contra Rucchi: El punto álgido del combate decisivo', 'CANON', 1),
       (303, '¿El criminal es Luffy Oyabun? En busca del cerezo gigante perdido', 'RELLENO', 1),
       (304, '¡Si no gano no podré proteger a nadie! Gia Sado activado', 'CANON', 1),
       (305, '¡El horrible pasado! La justicia oscura y Rob Rucchi', 'CANON', 1),
       (306, '¿Aparece una misteriosa sirena? A punto de perder el conocimiento', 'CANON', 1),
       (307, '¡La isla se hunde bajo el fuego! Los gritos de lamento de Franky', 'CANON', 1),
       (308, '¡Esperemos a Luffy! ¡Lucha sobre el Puente de la Vacilación!', 'CANON', 1),
       (309, '¡Los sentimientos mostrados con los puños! Luffy ejecuta el Gatoringu a la máxima potencia', 'CANON', 1),
       (310, '¡El amigo que viene desde el mar! El lazo de amistad más fuerte de la banda de Sombrero de Paja', 'CANON', 1),
       (311, '¡La gran huida juntos! El camino de la victoria es para los piratas', 'CANON', 1),
       (312, '¡Gracias, Merry! Nieve sobre el mar de las despedidas', 'CANON', 1),
       (313, '¡Descanso interrumpido! El vicealmirante de La Marina con el puño de amor', 'CANON', 1),
       (314, '¿El linaje familiar más fuerte? ¡Se desvela la identidad del padre de Luffy!', 'CANON', 1),
       (315, '¡Su nombre es Nuevo Mundo! La zona más remota de la Grand Line', 'CANON', 1),
       (316, '¡Shanks en movimiento! Ceremonia para la era salvaje', 'CANON', 1),
       (317, '¡La chica que busca a su Yagara! La gran investigación en la capital del agua', 'RELLENO', 1),
       (318, '¡Una madre debe ser fuerte! Las chorradas de Zoro ayudando en los queaceres domésticos', 'RELLENO', 1),
       (319, '¡Sanji se desploma! El misterioso anciano y su brillante cocina', 'MIXTO', 1),
       (320, '¡Todos tienen precio por su cabeza! ¡La banda que supera los 600 millones de berris!', 'CANON', 1),
       (321, '¡El rey de las bestias capaz de cruzar el Océano! ¡El barco de ensueño está terminado!', 'CANON', 1),
       (322, '¡Adiós a mis queridos seguidores! Franky se marcha', 'CANON', 1),
       (323, '¡Salida de la capital del agua! La decisión final de Usopp de su duelo entre hombres', 'CANON', 1),
       (324, '¡Las recompensas se extienden por el mundo! ¡En su tierra natal bailan y en su barco siguen avanzando!',
        'CANON', 1),
       (325, '¡La habilidad más poderosa! La oscuridad de Kurohige ataca a Ace', 'CANON', 1),
       (326, '¡La misteriosa banda de piratas! La peligrosa trampa en el Sunny', 'MIXTO', 1),
       (327, '¡El Sunny en peligro! Ruge, el mecanismo secreto de super velocidad', 'RELLENO', 1),
       (328, '¡El sueño hundido en el Nuevo Mundo! Pazul, el pirata desesperado', 'RELLENO', 1),
       (329, '¡Los asesinos atacan! Comienza la gran batalla sobre el hielo', 'RELLENO', 1),
       (330, 'Difícil batalla para la banda de Sombrero de Paja. En la bandera reside el alma del pirata', 'RELLENO',
        1),
       (331, '¡Calor a toda velocidad! El poder magnético de los gemelos se acerca', 'RELLENO', 1),
       (332, '¡La mansión del caos! El Don enfadado y la banda prisionera', 'RELLENO', 1),
       (333, '¡El renacer del fénix! El sueño de la bandera pirata que juramos juntos', 'RELLENO', 1),
       (334, '¡La decisiva batalla al rojo vivo! ¡Luffy contra el Don incandescente!', 'RELLENO', 1),
       (335, '¡El Nuevo Mundo nos espera! Hasta siempre, bravos piratas', 'RELLENO', 1),
       (336, '¡Chopperman en marcha! Proteged la costa de la emisora de TV', 'RELLENO', 1),
       (337, '¡Adentrándose en el mar diabólico! El misterioso esqueleto que llega entre la niebla', 'CANON', 1),
       (338, '¡El placer de encontrar a gente! Los auténticos sentimientos del esqueleto caballeroso', 'CANON', 1),
       (339, '¡Un fenómeno tras otro! ¡Desembarco en Thriller Bark!', 'CANON', 1),
       (340, '¡El hombre llamado genio! ¡Hogback aparece!', 'CANON', 1),
       (341, '¡Nami en serios apuros! La mansión zombi y el hombre invisible', 'CANON', 1),
       (342, '¡El zombi misterioso! ¡La sala de investigaciones del diabólico Hogback!', 'CANON', 1),
       (343, '¡Su nombre es Moria! La trampa del gran ladrón de sombras', 'CANON', 1),
       (344, '¡Festival en el Zombi Song! Las 12 campanadas son el sonido de la oscuridad', 'CANON', 1),
       (345, '¿Desbordados de animales? El Wonder Garden de Perona', 'CANON', 1),
       (346, '¡La banda de Sombrero de Paja desapareciendo! ¡Aparece un misterioso espadachín!', 'CANON', 1),
       (347, '¡El último caballero! El protector de Nami, el zombi traidor', 'CANON', 1),
       (348, '¡Llegando desde el cielo! ¡Ese hombre es el espadachín susurrante!', 'CANON', 1),
       (349, '¡Luffy en problemas! ¡El destino de la sombra más fuerte!', 'CANON', 1),
       (350, '¡El guerrero llamado demonio! Es la hora de que Oz resucite', 'CANON', 1),
       (351, '¡El despertar tras 500 años! ¡Oz revive!', 'CANON', 1),
       (352, '¡Una convicción lo bastante fuerte como para rogar por su vida! Brook protege su afro', 'CANON', 1),
       (353, '¡El juramento de un hombre jamás muere! Por el amigo que espera bajo un cielo lejano', 'CANON', 1),
       (354, '¡Nos volveremos a encontrar sin falta! Brook y el Cabo de la Promesa', 'CANON', 1),
       (355, '¡Comida, Nami y sombras! El contraataque del hambriento Luffy', 'CANON', 1),
       (356, '¿Usopp el más fuerte? Déjame a mi lo negativo', 'CANON', 1),
       (357, '¡Muerte repentina de los generales zombies! ¡Oz con ganas de aventuras!', 'CANON', 1),
       (358, '¡El caballero envuelto en llamas, Sanji! Destrozando a patadas la falsa ceremonia', 'CANON', 1),
       (359, '¿Una conexión invisible? El sueño robado de Sanji', 'CANON', 1),
       (360, '¡Héroe al rescate! El oponente es la princesa invencible', 'CANON', 1),
       (361, '¡Perona aterrada! La U de Uso es la U de Usopp', 'CANON', 1),
       (362, '¡Cortes que danzan sobre la azotea! Finaliza el Zoro contra Ryuuma', 'CANON', 1),
       (363, '¡La ira de Chopper! Las demoníacas prácticas médicas de Hogback', 'CANON', 1),
       (364, '¡Oz ruge! Da la cara, banda de Sombrero de Paja', 'CANON', 1),
       (365, '¡El enemigo es Luffy! El zombie más peligroso contra la banda de Sombrero de Paja', 'CANON', 1),
       (366, '¡Absalom derrotado! ¡El relámpago de la amistad de Nami!', 'CANON', 1),
       (367, '¡Consigamos un Down! Muerte segura: ¿Docking de los Sombrero de Paja?', 'CANON', 1),
       (368, '¡Una invasión silenciosa! El misterioso visitante: Kuma el Tirano', 'CANON', 1),
       (369, 'Oz + Moria: La combinación más fuerte de cerebro y fuerza física', 'CANON', 1),
       (370, 'Un giro con la estrategia secreta y la aparición de Nighmare Luffy', 'CANON', 1),
       (371, '¡La banda de Sombrero de Paja aniquilada! La habilidad Kage Kage al completo', 'CANON', 1),
       (372, '¡Comienza la batalla por la superioridad! Luffy contra Luffy', 'CANON', 1),
       (373, '¡La conclusión se acerca! Propiciando el golpe final', 'CANON', 1),
       (374, '¡Los cuerpos se desvanecen! ¡El Sol de la mañana ilumina la isla de las pesadillas!', 'CANON', 1),
       (375, '¡Crisis sin fin! Orden de eliminar a la banda de Sombrero de Paja', 'CANON', 1),
       (376, 'El poder de repelerlo todo, el poder Nikyu Nikyu de Kuma', 'CANON', 1),
       (377, 'El dolor de mis compañeros es mi dolor. Zoro lucha praparado para morir', 'CANON', 1),
       (378, 'La promesa de aquel lejano día. La canción de los piratas y la pequeña ballena', 'CANON', 1),
       (379, 'El pasado de Brook. Triste adiós a la alegre banda', 'CANON', 1),
       (380, 'El sake de Binks ¡La canción que conecta el pasado con el presente!', 'CANON', 1),
       (381, '¡Un nuevo compañero! ¡El músico Brook el Susurrante!', 'CANON', 1),
       (382, 'La amenaza Noro Noro. El regreso de Foxy el Zorro Plateado', 'RELLENO', 1),
       (383, '¡La gran competición del tesoro! ¡Derrumbamiento! El Spa land', 'RELLENO', 1),
       (384, 'La dura lucha de Brook. ¿El difícil camino para hacerse un verdadero Sombrero de Paja?', 'RELLENO', 1),
       (385, '¡Llegando a la mitad de la Grand Line! La Red Line', 'CANON', 1),
       (386, 'El que odia a la tripulación de los Sombrero de Paja. Entra Duval máscara de hierro', 'CANON', 1),
       (387, '¡La reunión predestinada! Salva al tritón encarcelado', 'CANON', 1),
       (388, '¡Tragedia! La verdad de Duval desenmascarada', 'CANON', 1),
       (389, '¡Explota! La nueva arma del Sunny-Go el Cañón Gaon', 'CANON', 1),
       (390, 'Llegada a la entrada a la isla Gyojin, el archipiélago Shabondy', 'CANON', 1),
       (391, '¡Tiranía! Tenryūbito, los gobernantes de Shabondy', 'CANON', 1),
       (392, '¡Los nuevos rivales se agrupan! Los once supernovas', 'CANON', 1),
       (393, '¡El objetivo es Camie! Se aproxima la mano del diablo de los secuestradores', 'CANON', 1),
       (394, 'Al rescate de Camie, la oscura historia del archipiélago', 'CANON', 1),
       (395, 'Límite de tiempo, comienza la subasta de personas', 'CANON', 1),
       (396, '¡El puño explosivo! Destruye la subasta', 'CANON', 1),
       (397, '¡Gran pánico! Pelea a muerte en el salón de la subasta', 'CANON', 1),
       (398, '¡El Almirante Kizaru avanza! El alborotado archipiélago Shaobody', 'CANON', 1),
       (399, '¡Atraviesa el sitio! Los marinos contra tres capitanes', 'CANON', 1),
       (400, 'Roger y Rayleigh - El Rey de los piratas y su mano derecha', 'CANON', 1),
       (401, '¿Imposible de evitar? La patada a la velocidad de la luz del Almirante Kizaru', 'CANON', 1),
       (402, '¡Aterrador! El arma de combate de la Marina, Pacifista', 'CANON', 1),
       (403, '¡Aparece otro enemigo fuerte! Sentōmaru, el empuñador del gran hacha', 'CANON', 1),
       (404, 'El feroz ataque del Almirante Kizaru - ¡La desesperación de los sombrero de paja!', 'CANON', 1),
       (405, 'La Tripulación desaparece, el último día de la tripulación de los sombrero de paja', 'CANON', 1),
       (406, 'Capítulo especial histórico, el jefe Luffy aparece de nuevo', 'RELLENO', 1),
       (407, 'Capítulo especial histórico ¡Destruye! la trampa del grupo Thriller', 'RELLENO', 1),
       (408, '¡Aterrizaje! Amazon Lily, la isla prohibida para los hombres', 'CANON', 1),
       (409, '¡Rápido! De vuelta a los compañeros, aventura en la isla de las mujeres', 'CANON', 1),
       (410, '¡Todos ebrios de amor! La emperatriz pirata Hancock', 'CANON', 1),
       (411, 'El secreto oculto en sus espaldas, Luffy se encuentra con la princesa serpiente', 'CANON', 1),
       (412, '¡Juicio sin piedad! ¡Margaret es convertida en piedra!', 'CANON', 1),
       (413, '¡La dura prueba de Luffy! ¡El poder del haki de las hermanas serpiente!', 'CANON', 1),
       (414, '¡Batalla con todo el poder de la habilidades! Gomu Gomu vs. Hebi Hebi', 'CANON', 1),
       (415, 'La confesión de Hancock, el pasado detestable de las hemanas', 'CANON', 1),
       (416, '¡Rescata a Ace! El nuevo destino es la gran prisión', 'CANON', 1),
       (417, '¡El amor es un huracan! Hancock enamorada', 'CANON', 1),
       (418, 'El paradero de los compañeros - Ciencia del clima y la isla de los mecanismos', 'MIXTO', 1),
       (419, 'El paradero de los compañeros - ¡La isla de los pájaros gigantes y el paraíso rosa!', 'CANON', 1),
       (420, 'El paradero de los compañeros - El puente que conecta islas y las plantas come hombres', 'MIXTO', 1),
       (421, 'El paradero de los compañeros - La princesa negativa y el rey demonio', 'MIXTO', 1),
       (422, '¡Una infiltración mortal! ¡La prisión submarina Impel Down!', 'CANON', 1),
       (423, '¡¿Una reunión en el infierno?! ¡El hombre que comió la Bara Bara No Mi!', 'CANON', 1),
       (424, '¡Atravesar el infierno carmesí! ¡El plan de inducción al caos de Buggy!', 'CANON', 1),
       (425, 'El hombre más fuerte en la prisión! Magellan el hombre Veneno aparece!', 'CANON', 1),
       (426, 'Especial relacionado con la película- Empieza a moverse. La ambición de Shiki', 'RELLENO', 1),
       (427, 'Especial relacionado con la película. Amenazan al pequeño East Blue', 'RELLENO', 1),
       (428, 'Especial de la película. El ataque de los piratas amigos', 'RELLENO', 1),
       (429, 'Especial relacionado con la película. ¡Batalla decisiva! Luffy vs Largo', 'RELLENO', 1),
       (430, '¡Un Shichibukai en la prisión! ¡Jimbei el primer hijo del mar!', 'CANON', 1),
       (431, 'La trampa del carcelero jefe Saldeath. Nivel 3, el infierno del hambre', 'CANON', 1),
       (432, '¡El cisne esta libre! ¡Una reunión con Bon Clay!', 'CANON', 1),
       (433, '¡Magellan, Guardián de la Estrategia! ¡Captura del Sombrero de Paja Completada!', 'CANON', 1),
       (434, '¡Todas las fuerzas se han reunido! La batalla en el Nivel 4 - ¡El infierno del calor ardiente!', 'CANON',
        1),
       (435, '¡El poderoso Magellan! Bon Clay huye', 'CANON', 1),
       (436, '¡El arreglo de cuentas ha llegado! ¡El desesperado último ataque de Luffy!', 'CANON', 1),
       (437, '¡Por su amigo! ¡Bon Clay va al Rescate!', 'CANON', 1),
       (438, '¡Un paraíso en el infierno! ¡Impel Down - Nivel 5.5!', 'CANON', 1),
       (439, '¡¡El tratamiento de Luffy comienza!! ¡El poder milagroso de Iva-san!', 'CANON', 1),
       (440, '¡Cree en los milagros! ¡Bon Clay Grita desde el Corazón!', 'CANON', 1),
       (441, '¡Volver! ¡El plan de fuga de Iva-san Comienza!', 'CANON', 1),
       (442, '!El convoy de Ace comienza!¡Batalla en el piso más bajo, Nivel 6!', 'CANON', 1),
       (443, '¡El Ultímate Team se ha formado! ¡Sacudir a Impel Down!', 'CANON', 1),
       (444, '¡Aun Mas caos! ¡Aquí viene Barbanegra Teach!', 'CANON', 1),
       (445, '¡Un encuentro peligroso! ¡Barbanegra y Shiryu de la lluvia!', 'CANON', 1),
       (446, '¡No hay un precio demasiado alto! ¡Hannybal serio!', 'CANON', 1),
       (447, '¡Un Jet Pistol lleno de ira! ¡Luffy vs. Barbanegra!', 'CANON', 1),
       (448, '¡Detener a Magellan! Estalla la técnica secreta de Iva-san', 'CANON', 1),
       (449, '¡El inteligente plan de Magellan! Frustrado el plan de fuga', 'CANON', 1),
       (450, 'El equipo de fugitivos en aprietos. El movimiento prohibido Venom Demon', 'CANON', 1),
       (451, 'Creando un último milagro. Atravesar la Puerta de la Justicia', 'CANON', 1),
       (452, 'Hacia el Cuartel General de la Marina. ¡Zarpando para rescatar a Ace!', 'CANON', 1),
       (453, 'El paradero de los nakamas. El pronostico de Weatheria y los animales cyborg', 'CANON', 1),
       (454, 'El paradero de los nakamas. El polluelo de pájaro gigante y un enfrentamiento rosa', 'CANON', 1),
       (455, 'El paradero de los nakamas. El Ejercito Revolucionario y la trampa del bosque de la gula', 'CANON', 1),
       (456, 'El paradero de los nakamas. La lápida gigante y la deuda de bragas', 'CANON', 1),
       (457, 'Un episodio especial en retrospectiva antes de Marine Ford. ¡El juramento de hermandad!', 'RELLENO', 1),
       (458, 'Un episodio especial en retrospectiva antes de Marine Ford. ¡Reúnanse! Los tres Almirantes', 'RELLENO',
        1),
       (459, '¡Se aproxima el momento de la batalla decisiva! La alineación más fuerte de la Marina en sus puestos',
        'CANON', 1),
       (460, 'Aparece una enorme flota. ¡Invasión! Los Piratas de Shirohige', 'CANON', 1),
       (461, '¡Comienza la batalla decisiva! El pasado de Ace y Shirohige', 'CANON', 1),
       (462, '¡Un poder capaz de destruir el mundo! La habilidad de la Gura Gura no Mi', 'CANON', 1),
       (463, '¡¡Todo reducido a cenizas!! ¡La habilidad del Almirante Akainu!', 'CANON', 1),
       (464, '¡Descendiente del demonio! ¡El pequeño Oars Jr. se precipita!', 'CANON', 1),
       (465, 'El vencedor será la justicia. ¡En marcha! La estrategia de Sengoku', 'CANON', 1),
       (466, 'Llega el equipo Sombrero de Paja. La tensión crece en el campo de batalla', 'CANON', 1),
       (467, 'Te salvaré aunque muera. Comienza la batalla Luffy vs. Marines', 'CANON', 1),
       (468,
        '¡Sucesión de batallas sin cuartel! Ejercito de usuarios de las habilidades vs. Ejercito de usuarios de las habilidades',
        'CANON', 1),
       (469, 'Kuma está extraño. El furioso golpe de Iva-san', 'CANON', 1),
       (470, 'Mihawk el maestro espadachín. Luffy se escabulle bajo el corte de la Kokutou', 'CANON', 1),
       (471, 'Comienza la operación de exterminio. El poder del ejército Pacifista', 'CANON', 1),
       (472, '¡La conspiración de Akainu! Shirohige cae en la trampa', 'CANON', 1),
       (473, '¡Inicia la operación de asedio! Los Piratas de Shirohige reducidos a una esquina', 'CANON', 1),
       (474, 'Se ha dado la orden de ejecución. ¡Atravesar el Muro de contención!', 'CANON', 1),
       (475, '¡Adentrándose en la última fase! Shirohige juega su triunfo para la remontada', 'CANON', 1),
       (476, '¡Luffy al límite de sus fuerzas! ¡¡Una guerra sin cuartel en la Plaza Oris!!', 'CANON', 1),
       (477, '¡Reducir la vida a cambio de poder! Usando una vez más la Tensión Hormonal', 'CANON', 1),
       (478, '¡Mantendré mi promesa! ¡Colisión! Luffy y Coby', 'CANON', 1),
       (479, '¡El patíbulo a tiro de piedra! ¡Se abre el camino hacia Ace!', 'CANON', 1),
       (480, 'Los diferentes caminos que elegimos ¡Luffy contra Garp!', 'CANON', 1),
       (481, '¡Ace liberado! ¡La última orden del capitán Shirohige!', 'CANON', 1),
       (482, '¡La energía que quema incluso el Fuego! El ataque despiadado de Akainu', 'CANON', 1),
       (483, 'En busca de una respuesta. Ace muere en el campo de batalla', 'CANON', 1),
       (484, '¡La sede de la Marina se desmorona! ¡La rabia silenciosa de Shirohige!', 'CANON', 1),
       (485, '¡Ajuste de cuentas! Shirohige contra los piratas de Kurohige', 'CANON', 1),
       (486, '¡El espectáculo comienza! Se revela el plan de Kurohige', 'CANON', 1),
       (487, '¡La tenacidad de Akainu! El puño de magma ataca a Luffy', 'CANON', 1),
       (488, '¡Un grito desesperado! Segundos de valor que cambian el destino', 'CANON', 1),
       (489, '¡Aparece Shanks! La guerra decisiva llega a su fin', 'CANON', 1),
       (490, '¡Poderosos rivales independientes! El comienzo de la Nueva Era', 'CANON', 1),
       (491, 'Llegada a la isla de las mujeres. Luffy se enfrenta a la cruda realidad.', 'CANON', 1),
       (492, '¡La combinación más potente! ¡La lucha de Luffy y Toriko!', 'RELLENO', 1),
       (493, 'Luffy y Ace ¡La historia del encuentro entre los hermanos!', 'CANON', 1),
       (494, '¡Aparece Sabo! El niño de Gray Terminal', 'CANON', 1),
       (495, '¡No huiré! ¡La desesperada operación de rescate de Ace!', 'CANON', 1),
       (496, '¡Algún día saldremos al mar! ¡El brindis de hermandad de los tres granujas!', 'CANON', 1),
       (497, '¿¡Adiós a la Familia Dadan!? ¡La base secreta está lista!', 'MIXTO', 1),
       (498, '¿¡Luffy aprendiz!? ¡El hombre que luchó contra el Rey de los Piratas!', 'MIXTO', 1),
       (499, '¡Duelo contra el tigre gigante! ¿¡Quién será el capitán!?', 'RELLENO', 1),
       (500, '¡Libertad robada! La trampa de los nobles se cierne sobre los tres hermanos.', 'CANON', 1),
       (501, '¡El fuego se extiende! Gray Terminal en peligro', 'CANON', 1),
       (502, '¿Donde está la libertad? La triste partida del niño', 'CANON', 1),
       (503, '¡Cuento contigo! La carta de un hermano', 'CANON', 1),
       (504, '¡Mantendré la promesa! Levando anclas por separado', 'CANON', 1),
       (505, '¡Quiero volver a verles! El llanto desconsolado de Luffy', 'CANON', 1),
       (506, '¡Los Sombrero de Paja conmocionados! La llegada de las terribles noticias', 'RELLENO', 1),
       (507, '¡Encuentro con el Rey Oscuro Rayleigh! Luffy debe tomar una decisión', 'CANON', 1),
       (508, '¡Volvamos con nuestro capitán! Fuga de la isla del cielo y el incidente en la isla de invierno', 'CANON',
        1),
       (509, '¡Encuentro! El gran espadachín Mihawk y la lucha desesperada de Zoro', 'CANON', 1),
       (510, '¡El sufrimiento de Sanji! ¡La Reina vuelve a su Reino!', 'CANON', 1),
       (511, '¡Un regreso inexplicable! Luffy en el Cuartel General de La Marina', 'CANON', 1),
       (512, 'Mensaje para los compañeros ¡Las grandes noticias llegan a ellos!', 'CANON', 1),
       (513, '¡Los piratas avanzan! El movidito Nuevo Mundo', 'CANON', 1),
       (514, 'Sobreviviendo en el infierno. La lucha de Sanji por su hombría', 'CANON', 1),
       (515, '¡Seré mucho más fuerte! ¡El juramento de Zoro a su capitán!', 'CANON', 1),
       (516, '¡Empieza el entrenamiento de Luffy! Nos veremos dentro de dos años, en el lugar pactado', 'CANON', 1),
       (517, '¡Comienza un nuevo capítulo! ¡Los Sombrero de Paja juntos de nuevo!', 'CANON', 1),
       (518, '¡Situación explosiva! Luffy contra el falso Luffy', 'CANON', 1),
       (519, 'Los marines de movilizan. El objetivo es la banda de Sombero de Paja', 'CANON', 1),
       (520, 'Reunión masiva. La amenaza de los falsos Sombrero de Paja', 'CANON', 1),
       (521, '¡Comienza la batalla! ¡Los resultados del entrenamiento!', 'CANON', 1),
       (522, 'Todos a bordo. Luffy da la señal para ir al Nuevo Mundo', 'CANON', 1),
       (523, 'Una verdad impactante. El hombre que protegió el Sunny', 'CANON', 1),
       (524, 'Estruendo submarino. Aparece el demonio de las profundidades', 'CANON', 1),
       (525, '¡Desastre en el fondo del mar! La banda de Sombrero de Paja dividida', 'CANON', 1),
       (526, '¡Volcán submarino en erupción! Aproximándose a la isla Gyojin', 'CANON', 1),
       (527, '¡Desembarco en la isla Gyojin! Las anheladas sirenas', 'CANON', 1),
       (528, '¡Erupción de placer! ¡Sanji en peligro de muerte!', 'CANON', 1),
       (529, '¿¡La isla Gyojin arrasada!? La predicción de Shyarly', 'CANON', 1),
       (530, 'El rey de la isla Gyojin ¡El dios del mar, Neptune!', 'CANON', 1),
       (531, '¡El palacio Ryuugu! El tiburón que salvamos a mitad de camino', 'CANON', 1),
       (532, '¡Cobarde y llorona! La princesa sirena de la torre Koukaku', 'CANON', 1),
       (533, '¡Estado de emergencia! ¡El palacio Ryuugu ha sido asaltado!', 'CANON', 1),
       (534, '¡El Palacio Ryuugu tiembla! ¡Shirahoshi es secuestrada!', 'CANON', 1),
       (535, 'La invasión de Hody. Comienza el plan de venganza', 'CANON', 1),
       (536, '¡Combate en el palacio Ryuugu! Zoro contra Hody', 'CANON', 1),
       (537, '¡Protegeré a Shirahoshi! ¡Decken se aproxima tras ella!', 'CANON', 1),
       (538, '¿¡La banda cae!? Hody conquista el palacio Ryuugu', 'CANON', 1),
       (539, '¡Destino resucitado! Nami y los piratas Gyojin', 'CANON', 1),
       (540, 'El héroe que liberó a los esclavos. Tiger, el aventurero', 'CANON', 1),
       (541, '¡Aparece Kizaru! Una trampa para Tiger', 'CANON', 1),
       (542, 'TorikoOne Piece Special: Team Formation! Save Chopper!', 'RELLENO', 1),
       (543, 'El final del héroe. La impactante verdad sobre Tiger', 'CANON', 1),
       (544, 'La banda pirata se dispersa. Jinbe contra Arlong', 'CANON', 1),
       (545, '¡La isla Gyojin se estremece! El Tenryuubito náufrago', 'CANON', 1),
       (546, '¡Una tragedia inesperada! La bala que robó el futuro', 'CANON', 1),
       (547, '¡Otra vez en el presente! Hody mueve ficha', 'CANON', 1),
       (548, '¡Gran sorpresa en el Reino! Orden de ejecutar a Neptune', 'CANON', 1),
       (549, '¡Surge el choque! Luffy contra Jinbe', 'CANON', 1),
       (550, 'La transformación de Hody ¡El verdadero poder de las Energy Steroids!', 'CANON', 1),
       (551, '¡Comienza la batalla decisiva en la plaza Gyoncord!', 'CANON', 1),
       (552, '¡Una impactante confesión! La verdad sobre el asesinato de Otohime', 'CANON', 1),
       (553, '¡Las lágrimas de Shirahoshi! Luffy hace su entrada', 'CANON', 1),
       (554, '¡Un gran choque! Los piratas de Sombrero de Paja contra 100.000 enemigos', 'CANON', 1),
       (555, '¡Explosión de habilidades! ¡Zoro y Sanji comienzan con su exhibición!', 'CANON', 1),
       (556, '¡Estreno! ¡Las armas secretas del Sunny!', 'CANON', 1),
       (557, '¡Pirata de hierro! Llega Franky Shogun', 'CANON', 1),
       (558, '¡Noah se acerca! ¡La isla Gyojin al borde de la destrucción!', 'CANON', 1),
       (559, '¡Date prisa, Luffy! Situación desesperada de Shirahoshi', 'CANON', 1),
       (560, '¡Comienza la encarnizada batalla! ¡Luffy contra Hody!', 'CANON', 1),
       (561, '¡Batalla campal! ¡La banda contra los Nuevos Piratas Gyojin!', 'CANON', 1),
       (562, '¿¡Luffy derrotado!? La venganza de Hody', 'CANON', 1),
       (563, '¡Una impactante revelación! ¡La verdadera naturaleza de Hody!', 'CANON', 1),
       (564, '¡Desde cero! ¡Una desesperada petición para Luffy!', 'CANON', 1),
       (565, '¡El gran puñetazo de Luffy! ¡El Halcón Rojo explota!', 'CANON', 1),
       (566, '¡La ansiada conclusión! Batalla final contra Hody', 'CANON', 1),
       (567, '¡Detened el Noah! ¡El desesperado Elephant Gatoringu!', 'CANON', 1),
       (568, '¡Hacia el futuro! El camino que sigue hacia el Sol', 'CANON', 1),
       (569, 'El secreto se revela. La verdad sobre el Arma Ancestral', 'CANON', 1),
       (570, '¡La tripulación sorprendida! ¡El nuevo almirante de flota de la Marina!', 'CANON', 1),
       (571, '¡La amante de los dulces! La Yonkou, Big Mom', 'CANON', 1),
       (572, 'Panorama desalentador. Una trampa aguarda en el Nuevo Mundo', 'CANON', 1),
       (573, '¡Partiendo al fin! Adiós, isla Gyojin', 'CANON', 1),
       (574, '¡Hacia el Nuevo Mundo! A por el mar más poderoso', 'CANON', 1),
       (575, 'La ambición de Z. ¡La pequeña gigante, Lily!', 'RELLENO', 1),
       (576, 'La ambición de Z. ¡Aparece el ejército secreto más poderoso!', 'RELLENO', 1),
       (577, 'La ambición de Z. ¡Estrategia de escape a la desesperada!', 'RELLENO', 1),
       (578, 'La ambición de Z. ¡Luffy contra Shuzo!', 'RELLENO', 1),
       (579, '¡En tierra! La isla en llamas, Punk Hazard', 'CANON', 1),
       (580, '¡Una abrasadora batalla! ¡Luffy contra el dragón gigante!', 'CANON', 1),
       (581, '¡La tripulación confundida! ¡La sorprendente cabeza de samurái!', 'CANON', 1),
       (582, '¡Conmoción! ¡Se desvela el secreto de la isla!', 'CANON', 1),
       (583, '¡Salvemos a los niños! ¡La banda entra en combate!', 'CANON', 1),
       (584, '¡Duelo de dominio con la espada! Brook contra el misterioso torso samurái', 'CANON', 1),
       (585, '¡El Shichibukai! Trafalgar Law', 'CANON', 1),
       (586, '¡Un lío tremendo! Luffy se hunde en el lago helado', 'CANON', 1),
       (587, '¡Choque! Law contra el vicealmirante Smoker', 'CANON', 1),
       (588, '¡Reunidos tras dos años! Luffy y Law', 'CANON', 1),
       (589, '¡Lo peor del mundo! El terrible científico, Caesar', 'CANON', 1),
       (590, 'La colaboración mas fuerte vs. el glotón de los mares', 'RELLENO', 1),
       (591, '¡Chopper entra en cólera! Los experimentos inhumanos del maestro', 'CANON', 1),
       (592, '¡La banda masacrada! El ataque de los legendarios asesinos a sueldo', 'CANON', 1),
       (593, '¡Salvaré a Nami! El combate de Luffy en la montaña nevada', 'CANON', 1),
       (594, '¡Es oficial! La alianza pirata entre Luffy y Law', 'CANON', 1),
       (595, '¡Atrapemos al maestro! ¡La alianza pirata inicia su plan!', 'CANON', 1),
       (596, '¡En riesgo de aniquilación! Aparece el monstruo de la muerte', 'CANON', 1),
       (597, '¡Una feroz batalla! Caesar revela su verdadera fuerza', 'CANON', 1),
       (598, '¡El samurai que corta el fuego! El Zorro de Fuego, Kinemon', 'CANON', 1),
       (599, '¡Noticia impactante! La identidad del hombre misterioso: Vergo', 'CANON', 1),
       (600, '¡Proteger a los niños! La mano demoníaca del Maestro se acerca', 'CANON', 1),
       (601, '¡Sacudiendo el Nuevo Mundo! El experimento de pesadilla de Caesar', 'CANON', 1),
       (602, '¡La peor arma de destrucción masiva de la historia! ¡Shinokuni!', 'CANON', 1),
       (603, '¡Empieza el contraataque! La gran fuga de Luffy y Law', 'CANON', 1),
       (604, '¡Directos al Bloque R! ¡Continúa el asalto de la alianza pirata!', 'CANON', 1),
       (605, 'Las lágrimas de Tashigi. La estrategia de avance suicida del G-5', 'CANON', 1),
       (606, 'El Vicealmirante traidor. El demonio del bambú, Vergo.', 'CANON', 1),
       (607, '¡Feroz batalla incandescente! ¡Luffy contra Caesar!', 'CANON', 1),
       (608, '¡Aquel que mueve los hilos desde la sombra! ¡Doflamingo entra en escena!', 'CANON', 1),
       (609, '¿¡Luffy muerto de frío!? ¡La aterradora mujer de las nieves, Monet!', 'CANON', 1),
       (610, '¡Enfrentamiento a puños! ¡Batalla de dos vicealmirantes!', 'CANON', 1),
       (611, '¡El pequeño dragón! Aparece Momonosuke', 'CANON', 1),
       (612, '¡Batalla invernal! ¡Los Sombrero de Paja contra la mujer de las nieves!', 'CANON', 1),
       (613, '¡Explota la técnica secreta! ¡El Ittoryuu más poderoso de Zoro!', 'CANON', 1),
       (614, '¡Protegeré a mis amigos! El desesperado escape de Mocha', 'CANON', 1),
       (615, '¡La frustración de Chahige! El ataque de ira de Luffy', 'CANON', 1),
       (616, '¡Impactante conclusión! ¡Smoker contra Vergo!', 'CANON', 1),
       (617, '¡Caesar derrotado! El poderoso Grizzly Magnum', 'CANON', 1),
       (618, '¡Invasión! Los asesinos de Dressrosa', 'CANON', 1),
       (619, '¡Enfrentamiento! El invencible Franky Shogun', 'CANON', 1),
       (620, '¡Desesperación total! Gran explosión en Punk Hazard', 'CANON', 1),
       (621, 'Capturar a Caesar ¡El General Cannon explota!', 'CANON', 1),
       (622, '¡Un emotivo reencuentro! Momonosuke y Kinemon', 'CANON', 1),
       (623, 'Triste despedida ¡Zarpando de Punk Hazard!', 'CANON', 1),
       (624, '¡El G-5 aniquilado! ¡La emboscada de Doflamingo!', 'CANON', 1),
       (625, '¡Tensión! Aokiji contra Doflamingo', 'CANON', 1),
       (626, '¡Caesar desaparecido! La alianza pirata en marcha', 'MIXTO', 1),
       (627, '¿¡Luffy se hunde en el mar!? La alianza pirata se derrumba', 'RELLENO', 1),
       (628, '¡Gran contraataque! ¡Los puños de ira de Luffy!', 'MIXTO', 1),
       (629, '¡Gran revuelo! Las increíbles noticias que sacuden el Nuevo Mundo', 'CANON', 1),
       (630, '¡Aventura! El país del amor y la pasión, Dressrosa', 'CANON', 1),
       (631, 'Frenesí en el Corrida Colosseum', 'CANON', 1),
       (632, 'Un peligroso amor. Violet la bailaora', 'CANON', 1),
       (633, '¡El guerrero desconocido más poderoso! Aparece Lucy', 'CANON', 1),
       (634, 'El pirata noble, Cavendish', 'CANON', 1),
       (635, 'Un reencuentro inesperado. Bellamy la Hiena', 'CANON', 1),
       (636, '¡Supernova! Bartolomeo el Caníbal', 'CANON', 1),
       (637, '¡Gran rivalidad! ¡La intensa batalla del Bloque B!', 'CANON', 1),
       (638, '¡Aplastante golpe! ¡El asombroso King Punch!', 'CANON', 1),
       (639, '¡El ataque de los peces luchadores! Atravesando el Puente de Hierro de la Muerte', 'CANON', 1),
       (640, '¡Aventura! La Isla de las Hadas, Green Bit', 'CANON', 1),
       (641, 'Un mundo desconocido. El reino Tontatta', 'CANON', 1),
       (642, 'El engaño del siglo. ¡El turno de Doflamingo!', 'CANON', 1),
       (643, '¡El cielo y la tierra tiemblan! El poder del Almirante Fujitora', 'CANON', 1),
       (644, '¡Un ataque furioso! Lucy contra el gigante', 'CANON', 1),
       (645, '¡El cañón destructor explota! Lucy en problemas', 'CANON', 1),
       (646, 'Un pirata legendario ¡Don Chinjao!', 'CANON', 1),
       (647, 'Luces y sombras ¡El lado oscuro de Dressrosa!', 'CANON', 1),
       (648, '¡Hacia la batalla! Usoland, el héroe legendario', 'CANON', 1),
       (649, '¡El clímax de la batalla! Lucy contra Chinjao', 'CANON', 1),
       (650, 'Luffy y la gladiadora predestinada Rebecca', 'CANON', 1),
       (651, '¡Yo te protegeré! Rebecca y el soldado de juguete', 'CANON', 1),
       (652, '¡El último gran campo de batalla! Comienza el Bloque D', 'CANON', 1),
       (653, '¡El combate decisivo! Giolla contra los Sombrero de Paja', 'CANON', 1),
       (654, '¡La espada hermosa! Cavendish del Caballo Blanco', 'CANON', 1),
       (655, '¡El gran choque! Sanji contra Doflamingo', 'CANON', 1),
       (656, '¡La técnica especial de Rebecca! Danza de la Espada en el Remanso', 'CANON', 1),
       (657, '¡El guerrero más temible! Logan contra Rebecca', 'CANON', 1),
       (658, '¡Sorpresa! La verdadera identidad del soldado de juguete', 'CANON', 1),
       (659, '¡Un pasado escalofriante! El secreto de Dressrosa', 'CANON', 1),
       (660, '¡Pesadilla! La noche trágica en Dressrosa', 'CANON', 1),
       (661, 'Duelo de Shichibukais. Law contra Doflamingo', 'CANON', 1),
       (662, '¡Los dos héroes cara a cara! Sombrero de Paja y el Demonio Celestial', 'CANON', 1),
       (663, 'Luffy sorprendido. El hombre que posee la voluntad de Ace', 'CANON', 1),
       (664, 'Empieza la Operación SOP. Usoland al ataque', 'CANON', 1),
       (665, '¡Pasión ardiente! Rebecca contra Suleiman', 'CANON', 1),
       (666, '¿¡Se ha decidido el ganador!? ¡El sorprendente final del Bloque D!', 'CANON', 1),
       (667, 'La decisión del almirante ¡Fujitora contra Doflamingo!', 'CANON', 1),
       (668, '¡Empieza el último round! ¡Aparece el héroe Diamante!', 'CANON', 1),
       (669, '¡El palacio se mueve! ¡Aparece el Gran Ejecutivo Pica!', 'CANON', 1),
       (670, '¡La Garra Dragón estalla! ¡El aterrador golpe de Lucy!', 'CANON', 1),
       (671, 'Hay que derrotar a Sugar ¡El ejército de enanos al ataque!', 'CANON', 1),
       (672, 'La última esperanza ¡El secreto de nuestro capitán!', 'CANON', 1),
       (673, 'El hombre reventón ¡La gran explosión de Gladius!', 'CANON', 1),
       (674, '¡El mentiroso Usoland decide huir!', 'CANON', 1),
       (675, 'Encuentro predestinado, Kyros y el Rey Riku', 'CANON', 1),
       (676, '¡La operación falla! ¿¡El héroe Usoland muere!?', 'CANON', 1),
       (677, '¡La leyenda regresa! El ataque sin cuartel de Kyros', 'CANON', 1),
       (678, '¡Estalla el puño de fuego! El poder de la Mera-Mera no Mi renace', 'CANON', 1),
       (679, 'Una entrada resplandeciente ¡El jefe de división del Ejército Revolucionario, Sabo!', 'CANON', 1),
       (680, 'La trampa del demonio. El plan de exterminio de Dressrosa', 'CANON', 1),
       (681, 'El hombre de los 500 millones ¡Usoland en el punto de mira!', 'CANON', 1),
       (682, 'Atravesando las líneas enemigas ¡El contraataque de Luffy y Zoro!', 'CANON', 1),
       (683, '¡La tierra tiembla! Aparece el gigantesco dios de la destrucción, Pica', 'CANON', 1),
       (684, '¡Gran reunión! Luffy y el ejército de fugitivos', 'CANON', 1),
       (685, '¡Continúa el asalto! ¡El ejército de Luffy contra Pica!', 'CANON', 1),
       (686, '¡Una impactante confesión! ¡La impetuosa promesa de Law!', 'CANON', 1),
       (687, '¡El gran choque! El jefe de división Sabo contra el Almirante Fujitora', 'CANON', 1),
       (688, 'Una situación desesperada ¡Luffy cae en una trampa!', 'CANON', 1),
       (689, '¡La gran fuga! El Elephant Gun de Luffy cambia las tornas', 'CANON', 1),
       (690, '¡Un frente unido! El avance de Luffy hacia la victoria', 'CANON', 1),
       (691, '¡Aparece el segundo samurái! Kanjuurou, de la Llovizna del Ocaso', 'CANON', 1),
       (692, 'Duelo encarnizado contra Pica ¡El ataque mortal de Zoro!', 'CANON', 1),
       (693, 'La princesa de los enanos, Mansherry cautiva', 'CANON', 1),
       (694, '¡Invencibles! El terrorífico ejército de cascanueces', 'CANON', 1),
       (695, '¡Arriesgando sus vidas! Luffy es la clave para la victoria', 'CANON', 1),
       (696, 'Reunión entre lágrimas ¡Rebecca y Kyros!', 'CANON', 1),
       (697, 'Donde pone el ojo, pone la bala ¡El hombre que salvará Dressrosa!', 'CANON', 1),
       (698, '¡La ira explota! El plan definitivo de Luffy y Law', 'CANON', 1),
       (699, '¡Una familia noble! La verdadera identidad de Doflamingo', 'MIXTO', 1),
       (700, 'El poder definitivo ¡El secreto de la fruta Ope Ope!', 'MIXTO', 1),
       (701, 'Recuerdos dolorosos ¡Law, el niño de la ciudad blanca!', 'MIXTO', 1),
       (702, '¡Tenryuubito! El escabroso pasado de Doffy', 'MIXTO', 1),
       (703, 'Una travesía tortuosa. El viaje vital de Law y Corazón', 'MIXTO', 1),
       (704, '¡Se acerca la hora! ¡A la caza de la fruta Ope Ope!', 'MIXTO', 1),
       (705, 'El momento de la resolución ¡La sonrisa de despedida de corazón!', 'MIXTO', 1),
       (706, 'Adelante, Law ¡El combate final del hombre bondadoso!', 'MIXTO', 1),
       (707, '¡Hacia la libertad! El Injection Shot de Law, desatado', 'CANON', 1),
       (708, '¡Una intensa batalla! Law contra Doflamingo', 'CANON', 1),
       (709, 'Enfrentamiento contra el ejecutivo. El orgulloso Hajrudin.', 'CANON', 1),
       (710, '¡La batalla del amor! El nuevo lider Sai contra Baby 5', 'CANON', 1),
       (711, '¡El orgullo de un hombre! ¡El último ataque de Bellamy!', 'CANON', 1),
       (712, 'El huracán explosivo ¡Hakuba contra Dellinger!', 'CANON', 1),
       (713, '¡Bari-Bari! ¡El Homage Shinken liberado!', 'CANON', 1),
       (714, 'La princesa sanadora ¡Salva a Mansherry!', 'CANON', 1),
       (715, '¡Duelo varonil! La elegía de amor de Señor', 'CANON', 1),
       (716, '¡Polvo de estrellas mortal! La violenta tormenta de ataques de Diamante', 'CANON', 1),
       (717, '¡Trueno Bastardo! ¡El furioso ataque de Kyros!', 'CANON', 1),
       (718, '¡Atravesando el suelo! ¡El ataque sorpresa del coloso de piedra, Pica!', 'CANON', 1),
       (719, 'Batalla decisiva en el aire ¡Estalla la técnica secreta mortal de Zoro!', 'CANON', 1),
       (720, '¡Hasta la vista! ¡El golpe de despedida de Bellamy!', 'CANON', 1),
       (721, '¿Law muerto? El ataque de furia de Luffy', 'CANON', 1),
       (722, 'Filo tenaz ¡El contraataque del Gamma Knife!', 'CANON', 1),
       (723, 'Choque de Haki ¡Luffy contra Doflamingo!', 'CANON', 1),
       (724, 'Inexpugnable ¡El asombroso secreto de Trébol!', 'CANON', 1),
       (725, 'Estallido de furia ¡Cargaré con el peso de todo!', 'CANON', 1),
       (726, '¡Gear Fourth! ¡El milagroso Boundman!', 'CANON', 1),
       (727, 'Gran contraataque ¡El despertar de Doflamingo!', 'MIXTO', 1),
       (728, '¡Luffy! ¡El definitivo Leo Bazooka!', 'CANON', 1),
       (729, '¡Kaen Ryou! ¡Protege la vida de Luffy!', 'CANON', 1),
       (730, 'Lágrimas milagrosas. ¡La batalla de Mansherry!', 'CANON', 1),
       (731, '¡Mientras nos quede aliento! ¡Detened la mortífera Jaula de Pájaros!', 'CANON', 1),
       (732, 'Vida o muerte, ¡Cuenta atrás del destino!', 'CANON', 1),
       (733, '¡Golpea los cielos! ¡El furioso King Kong Gun de Luffy!', 'CANON', 1),
       (734, '¡Libertad! ¡Dressrosa se levanta!', 'CANON', 1),
       (735, '¡Inaudito! ¡La sorprendente decisión del Almirante Fujitora!', 'CANON', 1),
       (736, 'El mundo tiembla ¡La Peor Generación sigue avanzando!', 'CANON', 1),
       (737, 'El nacimiento de una leyenda ¡Las aventuras del Guerrero Revolucionario Sabo!', 'MIXTO', 1),
       (738, 'El vínculo entre hermanos ¡El reencuentro entre Luffy y Sabo!', 'MIXTO', 1),
       (739, 'La criatura más poderosa. El Emperador Pirata Kaido de las Bestias', 'CANON', 1),
       (740, 'Fujitora mueve ficha ¡Asedio total a los Sombrero de Paja!', 'CANON', 1),
       (741, '¡Emergencia! ¡Rebecca ha sido secuestrada!', 'CANON', 1),
       (742, 'El vínculo de padre e hija ¡Kyros y Rebecca!', 'CANON', 1),
       (743, 'El orgullo de los hombres ¡Luffy y Fujitora cara a cara!', 'CANON', 1),
       (744, '¡Sin salida! ¡La implacable persecución del Almirante Fujitora!', 'CANON', 1),
       (745, '¡Los hijos beben sake! ¡La gran flota de Sombrero de Paja!', 'CANON', 1),
       (746, 'Los rivales se mantienen firmes. Los feroces monstruos del Nuevo Mundo', 'MIXTO', 1),
       (747, 'La fortaleza de plata. La gran aventura de Luffy y Bartolomeo', 'MIXTO', 1),
       (748, 'Un laberinto subterráneo. ¡Luffy contra el hombre vagoneta!', 'RELLENO', 1),
       (749, '¡La técnica de la espada candente! ¡Law y Zoro finalmente aparecen!', 'RELLENO', 1),
       (750, 'Una desesperada situación - La extrema batalla de Luffy', 'RELLENO', 1),
       (751, 'El comienzo de una nueva aventura - ¡Llegada a la isla misteriosa, Zou!', 'CANON', 1),
       (752, 'El nuevo Guerrero del Mar - El hijo del legendario Barbablanca aparece', 'CANON', 1),
       (753, '¡Una mortal subida al elefante! ¡La gran aventura en la parte trasera del elefante gigante!', 'CANON', 1),
       (754, '¡Comienza el combate! ¡Luffy vs. la Tribu Mink!', 'CANON', 1),
       (755, '¡Garchú! ¡Los Piratas de Sombrero de Paja se reúnen!', 'CANON', 1),
       (756, 'Comienza el contraataque - ¡Los grandes movimientos de los Piratas de Sombrero Rizado!', 'CANON', 1),
       (757, 'Una nueva amenaza - ¡Jack de los Piratas Bestias!', 'CANON', 1),
       (758, 'Rey del Alba - ¡El Duque Inuarashi aparece!', 'CANON', 1),
       (759, 'Rey de la Noche - Nekomamushi aparece', 'CANON', 1),
       (760, 'Destrucción de la capital - ¡Los Piratas de Sombrero Rizado llegan a tierra!', 'CANON', 1),
       (761, '¡Carrera contra el tiempo! - ¡El vínculo de los minks y la tripulación!', 'CANON', 1),
       (762, 'El bribón regresa a casa - El asesino de la Emperatriz Pirata Big Mom', 'CANON', 1),
       (763, 'La verdad detrás de su desaparición - La impactante invitación de Sanji', 'CANON', 1),
       (764, 'Para mis amigos - Nota de despedida de Sanji', 'CANON', 1),
       (765, 'Vamos a ver al Señor Nekomamushi', 'CANON', 1),
       (766, 'La decisión de Luffy - ¡Crisis por la renuncia de Sanji!', 'CANON', 1),
       (767, 'Una explosiva situación - ¡Gato, perro y samurái!', 'CANON', 1),
       (768, '¡La tercera parte! ¡Raizo el de la Niebla, el ninja, aparece!', 'CANON', 1),
       (769, '¡La piedra roja! La guía para el One Piece', 'CANON', 1),
       (770, 'El secreto del Reino de Wano. El Clan Kozuki y el Poneglyph', 'CANON', 1),
       (771, 'Una promesa de un hombre. Luffy y Kozuki Momonosuke', 'CANON', 1),
       (772, '¡El legendario viaje! ¡El perro, el gato y el Rey de los Piratas!', 'CANON', 1),
       (773, 'Regresa la pesadilla. Ataque del invulnerable Jack', 'CANON', 1),
       (774, 'Batalla defensiva de Zou. ¡Luffy y Zunisha!', 'CANON', 1),
       (775, 'Salvar al enorme elefante. ¡La operación de rescate de los de Sombrero de Paja!', 'RELLENO', 1),
       (776, 'Descendiendo el elfante. ¡Es hora de recuperar a Sanji!', 'CANON', 1),
       (777, 'Hacia el Reverie. ¡La princesa Vivi y la princesa Shirahoshi!', 'CANON', 1),
       (778, 'Hacia el Reverie. Rebecca y el Reino de Sakura', 'CANON', 1),
       (779, 'Kaido regresa. ¡La peor generación amenazada!', 'CANON', 1),
       (780, '¡Un frente hambriento! ¡Luffy y los marines supernovas!', 'RELLENO', 1),
       (781, 'El trío persistente. ¡La gran búsqueda de los de Sombrero de Paja!', 'RELLENO', 1),
       (782, 'Puño del diablo. ¡Enfrentamiento! Luffy contra Grount', 'RELLENO', 1),
       (783, 'Sanji regresa a casa. ¡Al territorio de Big Mom!', 'CANON', 1),
       (784, '0 y 4. Confrontación contra el Germa 66', 'CANON', 1),
       (785, 'La crisis del veneno mortal. Luffy y Reiju', 'CANON', 1),
       (786, '¡Totto Land! ¡Big Mom, uno de los Cuatro Emperadores aparece!', 'CANON', 1),
       (787, 'La hija de la emperatriz. La prometida de Sanji, Pudding', 'CANON', 1),
       (788, '¡Ataque masivo! ¡Los dolores de hambre de Mamá!', 'CANON', 1),
       (789, '¿La capital se desmorona? Big Mom y Jinbe', 'CANON', 1),
       (790, 'El castillo de uno de los Cuatro Emperadores. Llegada a Whole Cake Island', 'CANON', 1),
       (791, '¡El bosque de los dulces! Luffy contra Luffy', 'CANON', 1),
       (792, '¡El asesino de Mamá! Luffy y el Bosque de la Tentación', 'CANON', 1),
       (793, 'Una nación en el mar. Judge, el rey del Germa', 'CANON', 1),
       (794, 'Un enfrentamiento entre padre e hijo. ¡Judge contra Sanji!', 'CANON', 1),
       (795, 'Una gran ambición. Big Mom y Caesar', 'CANON', 1),
       (796, 'El reino de las almas. ¡El temible poder de Big Mom!', 'CANON', 1),
       (797, '¡El majestuoso comandante! Aparece uno de los tres comandantes dulces', 'CANON', 1),
       (798, 'Un enemigo de 800 millones. Luffy contra Mil Brazos Cracker', 'CANON', 1),
       (799, 'Duelo con toda su fuerza - Gear Fourth contra la habilidad Bisu Bisu', 'CANON', 1),
       (800, '1 y 2. ¡Reunión! La Familia Vinsmoke', 'CANON', 1),
       (801, 'Una vida de amabilidad. Sanji y el restaurante de Zeff', 'CANON', 1),
       (802, 'Un Sanji enfurecido. ¡El secreto del Germa 66!', 'CANON', 1),
       (803, 'El pasado que dejó atrás. Vinsmoke Sanji', 'CANON', 1),
       (804, 'Al East Blue. La determinada partida de Sanji', 'CANON', 1),
       (805, 'Una batalla de límites. Luffy y las galletas infinitas', 'CANON', 1),
       (806, 'El poder de la llenura. El nuevo Gear 4, Tankman', 'CANON', 1),
       (807, 'Un doloroso enfrentamiento. Luffy contra Sanji (1)', 'MIXTO', 1),
       (808, 'Un doloroso enfrentamiento. Luffy contra Sanji (2)', 'CANON', 1),
       (809, '¡Una tormenta de venganza! ¡Un ejército enfurecido viene a atacar!', 'CANON', 1),
       (810, 'El fin de la aventura. ¡La decidida proposición de Sanji!', 'CANON', 1),
       (811, '¡Yo esperaré aquí!. Luffy Vs. el ejercito enfurecido', 'CANON', 1),
       (812, '¡Infiltración en el castillo! ¡Roba el Road Phoneglyph!', 'CANON', 1),
       (813, 'Una confrontación fatídica. Luffy y Big Mom', 'CANON', 1),
       (814, 'El grito del alma. La operación relámpago de Brook y Pedro', 'CANON', 1),
       (815, 'Adiós. La llorosa determinación de Pudding', 'CANON', 1),
       (816, 'La historia del ojo izquierdo. Pedro contra Baron Tamago', 'CANON', 1),
       (817, '¡Cigarrillo húmedo! La noche antes de la boda de Sanji', 'CANON', 1),
       (818, 'El alma sin temor. Brook contra Big Mom', 'CANON', 1),
       (819, 'El deseo de Sora. El fracaso de Germa, Sanji', 'CANON', 1),
       (820, 'Sanji está de vuelta. El gran contraataque de Luffy', 'CANON', 1),
       (821, 'El castillo en confusión. ¡Luffy al punto de encuentro!', 'CANON', 1),
       (822, '¡La decisión de partir! Sanji y el bento de los Sombrero de Paja', 'CANON', 1),
       (823, '¡Traicionando a uno de los Cuatro Emperadores! ¡El gran plan para rescatar a Brook!', 'CANON', 1),
       (824, 'El encuentro. El uno contra uno al límite de Luffy', 'CANON', 1),
       (825, 'Mentiroso. Luffy y Sanji', 'CANON', 1),
       (826, 'Sanji vuelve. ¡Estruendo! La fiesta del té del infierno', 'CANON', 1),
       (827, '¡Una reunión secreta! Luffy contra los piratas Fire Tank', 'CANON', 1),
       (828, 'Un pacto mortal. ¡Las fuerzas aliadas de Luffy y Bege!', 'CANON', 1),
       (829,
        '¡Se revela el plan secreto de Luffy! ¡Justo antes de que se levante el telón! La ceremonia de boda de las conspiraciones',
        'CANON', 1),
       (830, 'La familia se reúne. ¡Se levanta el telón! La fiesta del té del infierno', 'CANON', 1),
       (831, 'La pareja rota. ¡Entran Sanji y Pudding!', 'CANON', 1),
       (832, '¡El beso de la muerte! Comienza el plan de asesinato de uno de los Cuatro Emperadores', 'CANON', 1),
       (833, '¡Ofreciendo una copa de sake! ¡El caballeroso Jinbe paga su deuda!', 'CANON', 1),
       (834, '¿El plan falla? ¡Los Piratas de Big Mom contraatacan!', 'CANON', 1),
       (835, '¡Corre, Sanji! ¡SOS Germa 66!', 'CANON', 1),
       (836, 'El secreto de mama. Elbaf y el Monstruo', 'CANON', 1),
       (837, 'El cumpleaños de Mama. El día que Carmel desapareció', 'CANON', 1),
       (838, '¡Los lanzacohetes en acción! El momento del asesinato de Mama', 'CANON', 1),
       (839, 'El ejercito maligno. ¡Transformación! Germa 66', 'CANON', 1),
       (840, '¡Cortando la Relación Padre-Hijo! ¡Sanji y Judge!', 'CANON', 1),
       (841, 'Escapando de la Fiesta del Té. Luffy contra Big Mom', 'CANON', 1),
       (842, 'Comieza la ejecución. ¿Los aliados aniquilados?', 'CANON', 1),
       (843, 'El castillo se derrumba. Comienza la huida', 'CANON', 1),
       (844, 'La lanza de Elbaf. ¡Embestida! La Big Mom voladora', 'CANON', 1),
       (845, 'La determinación de Pudding. ¡Ardiendo! Los bosques de la seducción', 'CANON', 1),
       (846, 'Un contraataque relámpago. ¡Nami y Zeus, la nube tormenta!', 'CANON', 1),
       (847, 'Una coincidencia de reunión. Sanji y la malvada Pudding enamorada', 'CANON', 1),
       (848, 'Salvad el Sunny. ¡Luchad con valor, Chopper y Brook!', 'CANON', 1),
       (849, 'Antes del amanecer. Pedro, el capitán de los Guardianes', 'CANON', 1),
       (850, 'Volveré. ¡La salida mortal de Luffy!', 'CANON', 1),
       (851, 'El hombre de los mil millones. El comandante sweet más fuerte, Katakuri', 'CANON', 1),
       (852, 'Empieza una dura batalla. Luffy contra Katakuri', 'CANON', 1),
       (853, 'El Green Room. El timonel invencible, Jinbe', 'CANON', 1),
       (854, 'La amenaza de Mogura. ¡La lucha silenciosa de Luffy!', 'CANON', 1),
       (855, '¿El final de la batalla mortal? El despertar de la ira de Katakuri', 'CANON', 1),
       (856, '¡El secreto prohibido! La merienda de Katakuri', 'CANON', 1),
       (857, '¡Luffy se defiende! ¡El punto débil del invencible Katakuri!', 'CANON', 1),
       (858, '¡Otra crisis! ¡Gearth Fourth contra Donas Imparables!', 'CANON', 1),
       (859, '¡La hija rebelde, Chiffon! ¡El gran plan de Sanji para transportar el pastel!', 'CANON', 1),
       (860, '¡La forma de vida de un hombre! ¡La determinación de Bege y Luffy como capitantes!', 'CANON', 1),
       (861, '¿El pastel se hundió? ¡La batalla de escape de Sanji y Bege!', 'CANON', 1),
       (862, '¡Sulong! ¡La gran transformación mística de Carrot!', 'CANON', 1),
       (863, '¡Ábrete paso! ¡La poderosa batalla naval de los Sombreros de Paja!', 'CANON', 1),
       (864, '¡Finalmente, se enfrentan! ¡La Emperatriz del Mar contra los Sombrero de Paja!', 'CANON', 1),
       (865, '¡Los preceptos directos del Rey Oscuro! ¡La batalla contra Katakuri da la vuelta!', 'CANON', 1),
       (866, '¡Finalmente regresa! ¡Sanji, el hombre que detendrá a la Emperatriz del Mar!', 'CANON', 1),
       (867, '¡Acechando en la oscuridad! ¡Un asesino apuntando a Luffy!', 'CANON', 1),
       (868, '¡La determinación de un hombre! ¡Katakuri arriesga su vida!', 'CANON', 1),
       (869, '¡Despierta! ¡El kenbunshoku haki que está a la altura de los más fuertes!', 'CANON', 1),
       (870, '¡Un puño de velocidad divina! ¡Otra aplicación del Gear Fourth activada!', 'CANON', 1),
       (871, '¡Finalmente, se acabó! ¡El clímax de la lucha intensa contra Katakuri!', 'CANON', 1),
       (872, '¡Una situación desesperada! ¡La trampa cerrada de Luffy!', 'CANON', 1),
       (873, '¡Alejándonos del apuro! ¡Los formidables refuerzos - Germa!', 'CANON', 1),
       (874, '¡La última esperanza! ¡Los Piratas del Sol emergen!', 'CANON', 1),
       (875, '¡Un sabor cautivador! ¡El pastel de la felicidad de Sanji!', 'CANON', 1),
       (876, '¡El hombre de la humanidad y la justicia! ¡Jinbe, una desesperada corriente masiva del océano!', 'CANON',
        1),
       (877, '¡La hora de partir! ¡El último deseo de Pudding!', 'CANON', 1),
       (878, '¡El mundo está aturdido! ¡El quinto emperador del mar emerge!', 'MIXTO', 1),
       (879, '¡A la Reverie! ¡Los aliados jurados de los Sombreros de Paja se juntan!', 'MIXTO', 1),
       (880, '¡Sabo entra en acción! ¡Aparecen todos los capitanes del ejército revolucionario!', 'CANON', 1),
       (881, '¡Entrando en acción! ¡El implacable nuevo almirante de la flota, Sakazuki!', 'RELLENO', 1),
       (882, 'La guerra de la cumbre. Voluntad heredada del Rey Pirata', 'MIXTO', 1),
       (883, 'Un paso por delante del sueño ¡El camino de Shirahoshi hacia el Sol!', 'MIXTO', 1),
       (884, '¡Lo extraño! ¡Los sentimientos de Vivi y Rebecca!', 'MIXTO', 1),
       (885, '¡En las tinieblas de la Tierra Santa! ¡Un misterioso sombrero de paja gigante!', 'MIXTO', 1),
       (886, 'La Tierra Santa, ¡La princesa Shirahoshi está siendo atacada!', 'CANON', 1),
       (887, 'En el borde. Los dos Emperadores apuntando a Luffy', 'MIXTO', 1),
       (888, 'Sabo se enfada. Tragedia del oficial del ejército revolucionario Kuma', 'MIXTO', 1),
       (889, '¡Finalmente, comienza! ¡El Reverie lleno de conspiración!', 'MIXTO', 1),
       (890, '¡Marco! ¡El guardián del último recuerdo de Barba Blanca!', 'MIXTO', 1),
       (891, '¡Subiendo por una cascada! ¡Un gran viaje por la tierra de la zona del mar de Wano!', 'CANON', 1),
       (892, '¡La tierra de Wano! ¡Al país de los samurai donde las flores de cerezo revolotean!', 'CANON', 1),
       (893, '¡Otama aparece! ¡Luffy contra el ejercito de Kaido!', 'CANON', 1),
       (894, '¡Él vendrá! ¡La Leyenda de Ace en la Tierra de Wano!', 'CANON', 1),
       (895, '¡Historia paralela! ¡El mejor cazarrecompensas del mundo, Cidre!', 'RELLENO', 1),
       (896, '¡Historia paralela! ¡Colisión! ¡Luffy contra Rey de la Carbonatación!', 'RELLENO', 1),
       (897, '¡Salva a Otama! ¡Sombrero de Paja, rebotando por el yermo!', 'CANON', 1),
       (898, '¡La estrella! ¡Hawkins el Mago aparece!', 'MIXTO', 1),
       (899, '¡La derrota es inevitable! ¡El feroz ataque de los Strawman!', 'CANON', 1),
       (900, '¡El mejor día de mi vida! ¡Otama y su dulce sopa de frijoles rojos!', 'CANON', 1),
       (901, '¡Carga contra el territorio del enemigo! ¡Ciudad de Bakura, donde los funcionarios prosperan!', 'CANON',
        1),
       (902, '¡Aparece el Yokozuna! ¡El invencible Urashima va tras Okiku!', 'MIXTO', 1),
       (903, '¡Una batalla climática de sumo! ¡Sombrero de paja contra el Yokozuna más fuerte!', 'CANON', 1),
       (904, '¡La ira intensa de Luffy! ¡Salva a Otama de la crisis!', 'CANON', 1),
       (905, '¡Luchando por Otama! ¡Lucha contra Holdem!', 'CANON', 1),
       (906, '¡Pelea! ¡El mago contra el cirujano de la muerte!', 'CANON', 1),
       (907, '¡20 Aniversario! Especial: Romance Dawn', 'RELLENO', 1),
       (908, '¡Llegada del barco del tesoro! ¡Luffy-tarou devuelve el favor!', 'CANON', 1),
       (909, '¡Misteriosas señales de lápidas! ¡Reunión en las ruinas del Castillo de Oden!', 'CANON', 1),
       (910, '¡El legendario Samurái! ¡El hombre que Roger admiró!', 'MIXTO', 1),
       (911, '¡Derrotar al Emperador del Mar! Comienza la operación de incursión secreta', 'CANON', 1),
       (912, '¡El hombre más fuerte! ¡El jefe del escuadrón de ladrones, Shutenmaru!', 'MIXTO', 1),
       (913, '¡Todos son aniquilados! ¡El aliento furioso de Kaido!', 'CANON', 1),
       (914, 'Finalmente se enfrentan. ¡El furioso Luffy contra Kaido!', 'MIXTO', 1),
       (915, '¡Destructivo! ¡Un golpe, una muerte: Raime Hakke!', 'MIXTO', 1),
       (916, '¡Un infierno viviente! ¡Luffy, humillado en la gran mina!', 'CANON', 1),
       (917, '¡Alboroto en la Tierra Santa! La risa maléfica del Emperador Barbanegra', 'MIXTO', 1),
       (918, 'Entra en acción. ¡El plan especial para derrotar a Kaido!', 'CANON', 1),
       (919, '¡Gran estruendo! ¡Los prisioneros Luffy y Kid!', 'CANON', 1),
       (920, '¡Una gran sensación! ¡El Soba Especial de Sanji!', 'CANON', 1),
       (921, '¡Elegante y magnífica! ¡La mujer más hermosa de Wano, Kumorasaki!', 'CANON', 1),
       (922, '¡Una historia de caballería! ¡El pequeño viaje de Zoro y Tonoyasu!', 'CANON', 1),
       (923, '¡Estado de emergencia! ¡Big Mom se acerca!', 'CANON', 1),
       (924, '¡La capital en alboroto! ¡Otro asesino va tras Sanji!', 'MIXTO', 1),
       (925, '¡Galante! ¡Soba Mask, el Justo!', 'CANON', 1),
       (926, '¡Una situación desesperada! ¡Los amenazantes Oniwabanshu de Orochi!', 'CANON', 1),
       (927, '¡Pandemonio! ¡El monstruo serpiente, Shogun Orochi!', 'CANON', 1),
       (928, '¡La flor cae! ¡Los momentos finales de la mujer más hermosa de la tierra de Wano!', 'CANON', 1),
       (929, 'El vinculo entre prisioneros ¡Luffy y el anciano Hyo!', 'CANON', 1),
       (930, '¡El cabeza de cartel! ¡Queen la Plaga aparece!', 'CANON', 1),
       (931, '¡Escalar! ¡El desesperado intento de Luffy por escapar!', 'CANON', 1),
       (932, '¡Vivo o muerto! El Sumo Infernal de Queen', 'CANON', 1),
       (933, '¡Gyukimaru! Zoro pelea un duelo en el puente de bandidos', 'CANON', 1),
       (934, '¡Un gran retorno! ¡El estilo de Tres Espadas supera el peligro!', 'MIXTO', 1),
       (935, 'Zoro asombrado ¡La identidad de la mujer misteriosa!', 'CANON', 1),
       (936, '¡Aprende el truco! ¡El Haki de la Tierra de Wano, Ryuo!', 'CANON', 1),
       (937, '¡Tonoyasu! ¡El más querido del pueblo Ebisu!', 'CANON', 1),
       (938, '¡Sacudiendo la nación! ¡La identidad de Ushimitsu Kozo, el ladrón caballeroso!', 'CANON', 1),
       (939, '¡Los sombreros de paja corren! ¡Salven al cautivo Tonoyasu!', 'CANON', 1),
       (940, 'La ira de Zoro. SMILE, la verdad tras la sonrisa', 'CANON', 1),
       (941, '¡Lágrimas de Toko! ¡Balas despiadadas de Orochi!', 'CANON', 1),
       (942, '¡Los Sombrero de Paja aparecen! Batalla en el patíbulo', 'CANON', 1),
       (943, '¡La determinación de Luffy! ¡Gana a través del Sumo Inferno!', 'CANON', 1),
       (944, '¡Llegó la tormenta! ¡Big Mom desbocada!', 'CANON', 1),
       (945, '¡Rencor por la sopa de frijol rojo! ¡Luffy está en una situación desesperada!', 'CANON', 1),
       (946, '¡Detén a la Yonkou! ¡El plan secreto de Queen!', 'CANON', 1),
       (947, '¡Munición brutal! ¡Las Balas Plaga van por Luffy!', 'CANON', 1),
       (948, '¡Empiecen la revuelta! ¡Luffy y los samuráis Akazaya!', 'CANON', 1),
       (949, '¡Vinimos a ganar! El grito desesperado de Luffy', 'CANON', 1),
       (950, '¡El sueño de los guerreros! ¡La conquista de Udon de Luffy!', 'CANON', 1),
       (951, '¡La persecución de Orochi! El Equipo Ninja contra Zoro', 'CANON', 1),
       (952, '¡Tensión aumentada en Onigashima! ¿Reunión? ¡Dos Emperadores del Mar!', 'CANON', 1),
       (953, '¡La revelación de Hiyori! Reunión en el Puente Oihagi', 'CANON', 1),
       (954, '¡Su nombre es Enma! ¡La grandiosa espada de Oden!', 'CANON', 1),
       (955, '¿Una nueva alianza? El ejército de Kaido se reúne', 'CANON', 1),
       (956, '¡Hacia la gran batalla! ¡Los Sombrero de Paja entran en modo de combate!', 'CANON', 1),
       (957, '¡Grandes noticias! ¡Un incidente que afecta a los Shichibukai!', 'CANON', 1),
       (958, '¡Una batalla legendaria! Garp y Roger', 'CANON', 1),
       (959, '¡El puerto prometido! ¡Comienza el tercer acto de la Tierra de Wano!', 'CANON', 1),
       (960, '¡El gran samurái de la Tierra de Wano! ¡Kozuki Oden aparece!', 'CANON', 1),
       (961, 'Aprendiz de lágrimas. ¡Oden y Kinemon!', 'CANON', 1),
       (962, 'Destino cambiante. ¡Aterrizan! ¡Los piratas de Barbablanca!', 'CANON', 1),
       (963, '¡La determinación de Oden! ¡La prueba de Barbablanca!', 'CANON', 1),
       (964, '¡El hermano menor de Barbablanca! ¡La gran aventura de Oden!', 'CANON', 1),
       (965, '¡Cruzando espadas! ¡Roger y Barbablanca!', 'CANON', 1),
       (966, '¡El deseo de Roger! Un nuevo viaje', 'CANON', 1),
       (967, '¡Dedicando su vida! La aventura de Roger', 'CANON', 1),
       (968, '¡Nace el Rey de los Piratas! ¡Llegada a la última isla!', 'CANON', 1),
       (969, '¡Rumbo a Wano! Los Piratas Roger se separan', 'CANON', 1),
       (970, 'Noticias tristes. Comienza la Gran Era Pirata', 'CANON', 1),
       (971, '¡Asedio! Oden y los Nueve Akazaya', 'CANON', 1),
       (972, '¡El fin de la batalla! ¡Oden contra Kaido!', 'CANON', 1),
       (973, 'Ejecutado en la olla. La lucha de una hora de Oden', 'CANON', 1),
       (974, 'El oden no sería oden si no estuviera hirviendo', 'CANON', 1),
       (975, '¡El castillo en llamas! ¡El destino del Clan Kozuki!', 'CANON', 1),
       (976, '¡De vuelta al presente! 20 años después', 'CANON', 1),
       (977, '¡El mar es para los piratas! ¡Asedio! A Onigashima', 'CANON', 1),
       (978, '¡Llega la Peor Generación! La Batalla del Mar Tormentoso', 'CANON', 1),
       (979, '¿Buena suerte? ¡El plan del líder Kinemon!', 'CANON', 1),
       (980, '¡Una promesa lacrimógena! Secuestran a Momonosuke', 'CANON', 1),
       (981, '¡Un nuevo miembro! ¡Primer Hijo del Mar Jimbei!', 'CANON', 1),
       (982, '¡La baza de Kaido! ¡Aparecen los Tobi Roppo!', 'CANON', 1),
       (983, '¡La seriedad de los samuráis! La tripulación llega a Onigashima', 'CANON', 1),
       (984, '¿Luffy pierde el control? Infiltración en el banquete de Kaido', 'CANON', 1),
       (985, 'Pensando en O-Tama. ¡El ataque furioso de Luffy!', 'MIXTO', 1),
       (986, '¡Batalla musical! ¡Una habilidad especial ataca a Luffy!', 'CANON', 1),
       (987, '¿Su sueño destrozado? ¡La trampa que atrae a Sanji!', 'CANON', 1),
       (988, '¡Llegan los refuerzos! ¡El comandante de los Piratas de Barbablanca!', 'CANON', 1),
       (989, '¡El pacto entre hombres! La feroz batalla del Brachio Tanque', 'MIXTO', 1),
       (990, '¡Raimei Hakke! La aparición del hijo de Kaido', 'CANON', 1),
       (991, '¿Amigo o enemigo? Luffy y Yamato', 'MIXTO', 1),
       (992, '¡El deseo de ser Oden! El sueño de Yamato', 'MIXTO', 1),
       (993, '¿Explosivo? ¡Las esposas que encadenan la libertad de Yamato!', 'CANON', 1),
       (994, '¡Enfrentamiento de los Vainas Rojas! Kikunojo contra Kanjuro', 'CANON', 1),
       (995, '¡Incursión! Heredando la voluntad de Oden', 'CANON', 1),
       (996, 'Estruendo en Onigashima. ¡Comienza la guerra total de Luffy!', 'CANON', 1),
       (997, '¡Batalla bajo la luna! ¡El poderoso Sulong!', 'CANON', 1),
       (998, '¿La traición de Zeus? ¡Nami está acorralada!', 'CANON', 1),
       (999, '¡Te protegeré! El encuentro entre Yamato y Momonosuke', 'CANON', 1),
       (1000, '¡Fuerza abrumadora! ¡Los Sombrero de Paja se reúnen!', 'CANON', 1),
       (1001, '¡Una invitación arriesgada! Un complot para destruir a Queen', 'CANON', 1),
       (1002, '¡Una nueva rivalidad! ¡Nami y Ulti!', 'CANON', 1),
       (1003, '¡Una espada heroica! ¡Los Vainas Rojas contra Kaido, otra vez!', 'CANON', 1);